### ISSUE TITLE
Bugs: & with macron and s cv38[5]

### ISSUE THREAD

**Issue by TheKnightWho** [psb1558/Junicode-font#114]
Hi,

1. I've noticed that the ampersand & doesn't seem to work properly with a macron. This is necessary for the abbreviation for etiam.

2. The long s with flourish (e[E8B7](https://mufi.info/m.php?p=muficharinfo&i=4389) or cv38[5]) still has the character width of a conventional long s. This is causing problems, because it's often followed by a superscript 'r' (seigneur). At the moment, that becomes hidden by the flourish, so I've had to manually increase the character spacing.

**Comment by psb1558** [comment]
1. I'll add an anchor, which should fix the problem.
2. I'll fix the width and add kerning to fix the superscript problem.

Will close this when the fixes are in the  repository.

**Comment by TheKnightWho** [comment]
Thanks!

**Comment by psb1558** [comment]
Fixed now.
<img width="374" alt="image" src="https://user-images.githubusercontent.com/16215767/158163897-38ae51c3-afde-4279-aef4-5e76710e9a0b.png">
