### ISSUE TITLE
Quote Kerning

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Junicode-font#116]
It appears that no kerning pairs have been made for quotation marks.
![kerning problems](https://user-images.githubusercontent.com/65306291/156938417-293cc221-fcfc-4725-9915-9b9003e864d0.png)
The same problems appear with double quotation marks, and seem deserving of improvement. Capital A is the worse case, but most of the letters could be better.
### Addendum:
I didn't think to check, but there's also an issue with kerning between closing quotation marks and the letters that follow. These pairs show up in contractions often enough, and the frequent ’s combination looks like the s isn't part of the word.

**Comment by psb1558** [comment]
Yes, almost all the kerning right now is between letters, very little for punctuation, brackets, numbers, etc. It's on the to-do list and I will get to it.

**Comment by psb1558** [comment]
This has now been done for single and double qu. marks (they have the same metrics) with basic Latin and a few other characters. Roman--not yet italic.

A few weeks ago someone sent me a kerning test document that covers unusual (at least in English) combinations. I'll be going through that in the next few weeks.

**Comment by eclecticfluff** [comment]
Wow, that’s astoundingly fast. It’s great to hear that progress on the font is going so quickly.
