### ISSUE TITLE
Combining tilde overlay with capital Q

### ISSUE THREAD

**Issue by TheKnightWho** [psb1558/Junicode-font#127]
Hi - this is another slightly awkward situation with the combining overlay tilde, but this time with capital Q:
![image](https://user-images.githubusercontent.com/6895210/159453333-9a76a57d-c3bf-4159-976d-f846eeb43ac6.png)

This comes from the [Articles of the Barons](https://earlyenglishlaws.ac.uk/laws/manuscripts/ao/?tp=s&nb=2537), which clearly shows that the line is through the (equivalent of the) descender:
![image](https://user-images.githubusercontent.com/6895210/159453411-1004a206-d4b1-4ef8-a44e-c22c9c161e5c.png)

I've noticed that Junicode handles lowercase q similarly to U+A757 (ꝗ) - though I think the stroke lengths are slightly different - but this isn't the case for uppercase Q with U+A756 (Ꝗ):
![image](https://user-images.githubusercontent.com/6895210/159454543-9cb27ba3-9803-4b4e-8da4-0c2405775622.png)

While I could use U+A756, I'm not sure that that would be being faithful to the intention of the Record text, which makes this another one of those awkward situations like capital H where I'm trying to work out what the Record Commission/printer would have done in an ideal world. I'm also concerned about text searchability, which is why I've been trying to avoid precomposed characters wherever possible.

**Comment by psb1558** [comment]
There are no [normalization](https://unicode.org/charts/normalization/) sequences for these q-with-stroke Unicode characters, but if there were, I'd say U+A756/7 would probably decompose to Qq + U+0335 (or U+0334) and U+A758/9 would decompose to Qq + U+0337.

If this seems right, I will put in some ccmp rules that will fix these sequences, e.g. Q + U+0334 becomes U+A756 (Ꝗ). That would solve the searchability problem.

**Comment by psb1558** [comment]
Okay, I've added these rules:
<img width="217" alt="image" src="https://user-images.githubusercontent.com/16215767/159474001-d4926e77-6834-4d16-be67-8ccf7f50d8f4.png">
Rules for q + U+0334/5 didn't seem necessary. Since `ccmp` is an always-on feature, most apps will handle these substitutions invisibly.

I'll build a new version next weekend, and the new rules will be available then.

**Comment by TheKnightWho** [comment]
Fab - thank you again for the lightning turnaround.

**Comment by psb1558** [comment]
Fixed now.
