### ISSUE TITLE
Reposition U+0323 "Combining dot below" with U+035F "Double macron below"

### ISSUE THREAD

**Issue by adamiturabi** [psb1558/Junicode-font#136]
Thank you for this great font.

With Junicode Two Beta v1.049, I have entered the following input sequence:

U+0064 "d"
U+035F "Double macron below"
U+0323 "Combining dot below"
U+0068 "h"

Here is an image of what is displayed:

![image](https://user-images.githubusercontent.com/61895563/167297743-e596d402-b61f-420d-bf4e-3aa26d62c26a.png)

Would it be possible to reposition the dot below the macron thus:

![image](https://user-images.githubusercontent.com/61895563/167297478-4749df12-2043-4af5-8ea1-ca4dcb02c46e.png)

Or is there an existing input sequence that would allow me to achieve what I'm looking for?

Thank you!

**Comment by psb1558** [comment]
To do this, I would need to add a new glyph to the font. Can you say something about what this is for, and what the likelihood is that others would want it? Does it appear in print anywhere?

**Comment by psb1558** [comment]
With no response from the poster, I am closing this now.
