### ISSUE TITLE
Latin letters glottal I/A/U: U+A7BA-U+A7BF 

### ISSUE THREAD

**Issue by dwerning** [psb1558/Junicode-font#141]
This is a reminder that there is still urgend demand for 
U+A7BC LATIN CAPITAL LETTER GLOTTAL I
U+A7BD LATIN SMALL LETTER GLOTTAL I
= egyptological yod
![grafik](https://user-images.githubusercontent.com/33833393/175248497-391ba289-ece0-4665-8627-12a3a8767e47.png)
in the Egyptological community.
See https://sourceforge.net/p/junicode/feature-requests/61/

**Comment by psb1558** [comment]
Sorry this took a while. Do these look okay?
<img width="904" alt="image" src="https://user-images.githubusercontent.com/16215767/182007952-4dbc9f17-a0c6-4fc2-ae49-f236ff85fd8a.png">

**Comment by dwerning** [comment]
That looks perfect from Egyptological perspective. Thank you.
