### ISSUE TITLE
Some additional IPA display not will.

### ISSUE THREAD

**Issue by kanmurimori** [psb1558/Junicode-font#142]
![image](https://user-images.githubusercontent.com/20810895/183395451-08fd3002-3114-487b-af44-6e748f13d195.png)

like β̞ ɰ͍ʲ ɯ̟ᵝ

**Comment by psb1558** [comment]
Fixed fonts now in the repository. I still need to add anchors for IPA characters other than those requested in this issue.

**Comment by kanmurimori** [comment]
@psb1558  ɤ̈
![image](https://user-images.githubusercontent.com/20810895/193401659-80b3059a-2ae7-4fc2-b1a4-3ab4130c0c1e.png)
