### ISSUE TITLE
U+2E17 missing in bold and bold-italic

### ISSUE THREAD

**Issue by dwerning** [psb1558/Junicode-font#143]
The sign U+2E17 `⸗` is fine in normal, and italic, but apparently missing in bold and bold-italic (and others?).
JunicodeTwobeta, ttf, v.1.052

**Comment by psb1558** [comment]
It's in all the roman faces, still missing in italic (which is more than 100 glyphs short of complete). I'll add it soon.

**Comment by psb1558** [comment]
This is done now; but it will still be a while before the italic face is complete.

**Comment by dwerning** [comment]
Dear Mr. Baker,
Thank you. Just as a stimulus: Egyptology _always_ renders its transliterations in italics, at least in print. It is therefore especially desirable for us to find italics in the near future.
Greetings!
[JuniCode Two Beta-v1.053.pdf](https://github.com/psb1558/Junicode-font/files/9439477/JuniCode.Two.Beta-v1.053.pdf)

**Comment by psb1558** [comment]
Can you tell me something about what the highlighted bits are supposed to look like? When I copy and analyze the sequence from the PDF, I get . . . confusion.

Most of this looks like issues with anchors, which are easily fixed.

**Comment by dwerning** [comment]
Indeed, I cannot reproduce the ill appearance pdf anymore now. It was probably a temporary confusion of my Word2013 directly after installing the font -- it was, as I had forgotten to mention, not in Word itself but only in the Adobe Acrobat export file). Now everything seems fine and beautiful. Sorry for the extra work that I have caused.

**Comment by psb1558** [comment]
No problem! I'm glad it's working now.
