### ISSUE TITLE
Bold is broken in Junicode v1.003

### ISSUE THREAD

**Issue by HM3p** [psb1558/Junicode-font#153]
While selecting bold on a text in LibreOffice Writer, it becomes bold italic.
![Screenshot 2022-11-10 120138](https://user-images.githubusercontent.com/80926527/201159463-8c38369d-9f26-481d-85c2-0806eb1062f1.png)

**Comment by alexmyczko** [comment]
what os/release? which version of libreoffice? does the font selector show multiple Junicode instances?

**Comment by kenmcd** [comment]
The Bold font had the weight set to SemiBold (600).
Even though the style linking is correct, this appears to have confused LibreOffice.
When I set the Bold weight to 700 it seems to have fixed this.
Tested on LibreOffice v7.4.2.3 on Windows 10.
Try these: 
[Junicode.v1.003.fixed.Bold.weight.zip](https://github.com/psb1558/Junicode-font/files/10077024/Junicode.v1.003.fixed.Bold.weight.zip)

**Comment by psb1558** [comment]
I'll check on the things @kenmcd has mentioned and anything else (like the names table) that could be causing the problem.

**Comment by kenmcd** [comment]
> I'll check on the things @kenmcd has mentioned and anything else (like the names table) that could be causing the problem.

The names looked fine which is why this is so odd.

**Comment by HM3p** [comment]
> The Bold font had the weight set to SemiBold (600). Even though the style linking is correct, this appears to have confused LibreOffice. When I set the Bold weight to 700 it seems to have fixed this. Tested on LibreOffice v7.4.2.3 on Windows 10. Try these: [Junicode.v1.003.fixed.Bold.weight.zip](https://github.com/psb1558/Junicode-font/files/10077024/Junicode.v1.003.fixed.Bold.weight.zip)

It works, thank you very much!

**Comment by psb1558** [comment]
Sorry to be sluggish about working on this, and thanks very much for the fix. I've pushed a new bold font to the Junicode-One branch.
