### ISSUE TITLE
Add character variant for uppercase Q

### ISSUE THREAD

**Issue by amarakon** [psb1558/Junicode-font#157]
Personally, I prefer a Q that sort of looks like a 2, similar to the one in TeX Gyre Pagella and Libertinus Serif. I attached an image. Take a look at Row 2 Column 3-4.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Q_typographic_styles.svg/512px-Q_typographic_styles.svg.png)

Could you add a character variant for the uppercase Q?

**Comment by psb1558** [comment]
It would be out of character for this typeface--sorry. But the italic already has a nice 2-shaped swash, based on the early models:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/16215767/219355603-426d4b3f-df88-4cb3-b816-b080d743cbfc.png">

**Comment by amarakon** [comment]
What I mean is something similar to Libertinus Serif, where the circle of the Q is still closed, but the line goes straight from the bottom of the circle and then to the right. As apposed to the more common diagonal line, this looks better in my opinion. Is that still out of character for Junicode?

**Comment by psb1558** [comment]
I've been thinking about this for a while. In general, I am glad to include variant letter-forms when someone has a practical use for them--for example, a several varieties of slashed o for Old Polish. And I include variants I find in the Fell typefaces that are models for Junicode--for example, swashes for the Italic. This is different. It's about a personal stylistic preference, one that's not modeled in the Fell types, and there my attitude is that the style of Junicode is what it is.

That said, Junicode is Open Source, and you are completely free to alter it in any way you see fit.

I'm closing this now.

**Comment by amarakon** [comment]
Thanks, I completely understand now.
