### ISSUE TITLE
Apostrophe is too close to previous letter

### ISSUE THREAD

**Issue by amarakon** [psb1558/Junicode-font#158]
When typing an apostrophe in the middle of a word, like in the word "Qur’an", the apostrophe seems to be too close to the character that comes before it.

**Junicode 2 Beta:**

![import-2023-02-18_05:25:48](https://user-images.githubusercontent.com/92645199/219855376-4077f31d-d778-4086-8065-e7c6efd90441.png)

**EB Garamond:**

![import-2023-02-18_05:27:00](https://user-images.githubusercontent.com/92645199/219855433-7045bd1b-3694-4809-adcb-c959f03dc265.png)

**Comment by psb1558** [comment]
This is a kerning issue. I'll take care of it.

**Comment by psb1558** [comment]
I'll be posting a new build of the font this weekend.
<img width="256" alt="image" src="https://user-images.githubusercontent.com/16215767/224309205-887cefec-5543-4938-89fc-e99451e7381f.png">

**Comment by amarakon** [comment]
Great, thanks.

**Comment by psb1558** [comment]
Fonts with this fix are now in the repository.

**Comment by amarakon** [comment]
Thanks, it looks much better now.
