### ISSUE TITLE
b and l with loop

### ISSUE THREAD

**Issue by mbudaj** [psb1558/Junicode-font#161]
Hi,

would it be possible to add alternate shapes for _b_ and _l_ with a loop (which were added in #27). When used in Czech typography, there was no swash to the left. Also, the upper loop of _b_ joined the lower one.

I attach a picture containing both regular shapes (underlined blue) and looped shapes (underlined green). Although this sample is in Schwabacher, it would be useful to have analogous shapes for transcriptions in the Roman type.

![b_l](https://user-images.githubusercontent.com/10212561/224116980-83c24b7a-0ce7-41f6-b1b6-0d28b91857f2.jpg)

Regarding looped _b_ and _l_ implemented in Junicode, there is a **bug** in building ſ-ligatures, reported in a comment to a [closed issue](https://github.com/psb1558/Junicode-font/issues/27#issuecomment-1382840395), so I reference it here for a better visibility.

**Comment by psb1558** [comment]
These are common shapes in early printing based on late gothic, and they may be useful for people working with various late medieval/early modern languages.
<img width="281" alt="image" src="https://user-images.githubusercontent.com/16215767/224131651-d2f3ae9a-91a9-4a1e-8452-694f2acd34cc.png">
**b with loop** will be available via cv04[2] and **l with loop** via cv24[5].

**Comment by mbudaj** [comment]
Nice design, thank you!

**Comment by psb1558** [comment]
Fonts with these characters/features are now in the repository (version 1.055).
