### ISSUE TITLE
Lowercase b with dot above in Irish: ḃ

### ISSUE THREAD

**Issue by silmeth** [psb1558/Junicode-font#169]
In the [Irish test file](https://github.com/psb1558/Junicode-font/blob/master/docs/Irish_test.pdf) and also when using Junicode Two Beta (tested with 1.049) with the `ss02` feature, the dot above ⟨b⟩ is displayed above the ascender while typically in Irish typography and manuscripts it’s rather next to the ascender, above the bowl – not above the ascender line.

The test file looks **really great** compared to the old Junicode with ss02 when rendering Irish texts with the ⟨ḋ, ṫ, ġ, ṡ⟩ characters – but this ⟨ḃ⟩ is still off and looks weird.

In the test pdf it looks like this:
![ḃ with dot above the ascender](https://user-images.githubusercontent.com/5329644/233656844-b1b2f059-a45f-474b-9a0a-d2c6fff994ee.png)

while I’d rather expect something like this:
![ḃ with dot above the bowl](https://user-images.githubusercontent.com/5329644/233656765-67079997-e189-46db-a638-71aea619a441.png)

See [here](https://wikisource.org/wiki/Page:T%C3%A1in_B%C3%B3_Cuailnge_%27na_dr%C3%A1ma_-_Ua_Laoghaire.pdf/15) for early 20th c. print example:

![Meiḃ, ḃainean, from PUL’s Táin ’na dhráma](https://user-images.githubusercontent.com/5329644/233659041-dec00d6f-98ac-4482-b25c-f2ffc7c4180f.png)

Interestingly enough, with the old Junicode used on Wikisource this one glyph is actually rendered as I’d expect:

![Méiḃ, ḃainean, ḃfuilir in old Junicode:ss02](https://user-images.githubusercontent.com/5329644/233666647-73104d61-5e2f-4292-848f-9fb0b4ce4cd2.png)

## Other examples ##

See how [Gaelchló](https://www.gaelchlo.com/clonna1.html) fonts handle this, none of them has the dot above the ascender line:

![Gaelchló website](https://user-images.githubusercontent.com/5329644/233660430-95bb07a1-f17e-4f66-aada-5465e5028474.png)

An example from early 18th c. Irish print (Mac Curtin’s grammar):
![article declension, “The Elements of the Irish Language”, p. 28](https://user-images.githubusercontent.com/5329644/233660077-3f84d337-58cb-4774-86db-f5e752b20cd2.png)

Another early (19th c.?) print example (not sure what the source is, actually):

![obraz](https://user-images.githubusercontent.com/5329644/233661987-5e2eddca-ec72-4d1d-b58c-0aed0da9a799.png)

Print of Bedell’s Bible, early 19th c.:

![obraz](https://user-images.githubusercontent.com/5329644/233662961-22d71170-2886-4e72-b8e8-cd76bac85f5e.png)

Early 17th c. manuscript ([RIA MS 24 P 8](https://www.isos.dias.ie/RIA/RIA_MS_24_P_8.html), the main *Irish Gramamtical Tracts I* ms.):
![IGT I ms.](https://user-images.githubusercontent.com/5329644/233664417-3dc5a46b-e414-480a-b58b-f56bd8ac80dc.png)

And an early 20th c. cursive example (from [Bailiúchán na scol, dúchas.ie](https://www.duchas.ie/en/cbes/4427879/4353580)):
![obraz](https://user-images.githubusercontent.com/5329644/233665301-18d0995b-a275-42be-9f8e-bd34096ae6ca.png)

**Comment by psb1558** [comment]
My understanding was that the position of the dot in Junicode 1 was not canonical, but of course the positioning of diacritics can be language-specific. I've created an alternate shape of bdotaccent (U+1E03) and added it to the ss02 lookup for Irish.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/16215767/233711713-ed1e3f1c-b1c9-4c3b-ace2-4a210776bbe8.png">
<img width="560" alt="image" src="https://user-images.githubusercontent.com/16215767/233711808-93e118a5-70d7-425d-b9de-8cc1d423be75.png">
These will be in the next build of Junicode 2 (1.058), probably within the next week or so.

**Comment by silmeth** [comment]
Thanks!

Not sure what the canonical placement is, but for whatever it’s worth the [Unicode chart](https://www.unicode.org/charts/PDF/U1E00.pdf) displays the dot next to the ascender above the bowl too:
![](https://user-images.githubusercontent.com/5329644/233715460-fe5f747b-9531-4786-b53d-acc0daf08321.png)

**Comment by psb1558** [comment]
I don't know what other languages the letter might be used in, but only the usage of the fonts I think of as most authoritative. In any case, it will now be correct in Irish text.

**Comment by silmeth** [comment]
Out of curiosity, what are some of the fonts you consider authoritative?

**Comment by psb1558** [comment]
It's a good question, because it prompted me to do a survey of the treatment of that character by various fonts. It seems the majority view is that the dot of U+1E03 should be sitting at the same height as the dot of an i, so that's what I'll do (esp. since I have no evidence that the character is used in any language aside from Irish).
But here are the fonts I refer to most often:
- Brill. Professionally created for the publishing house by one of the leading designers in the font industry.
- Gentium. An Open Source font informed by a good bit of deep research. It covers all languages using the Latin, Greek, and Cyrillic scripts.
- Bembino. A good font made under the supervision of academics and meant to serve the academic world.
- Noto. A large family of fonts covering many scripts.
- Andron. The reference font for the Medieval Unicode Font Initiative. Also an incredibly fine design.

There are more, but these are the ones that have U+1E03.

**Comment by silmeth** [comment]
@psb1558 Regarding the upper-case Ḃ (following from https://github.com/psb1558/Junicode-font/issues/170#issuecomment-1518636080), a counterexample to what I said there.

There’s Petrie’s typeface (~first half of the 19th c.) which has separate shape for lowercase b and for capital B, and the dot for the capital one is much higher there:

![](https://user-images.githubusercontent.com/5329644/233968634-c3692fa4-9956-4cb0-8b6c-1a2dafb0d0d7.png)

And here’s digital take at reproducing this by Gaelchló, their [Ríchló GC font](https://www.gaelchlo.com/rigc.html):

![](https://user-images.githubusercontent.com/5329644/233968021-f29a193a-3c99-42a5-8ae4-4ca249b9c764.png)

It seems to me that this is to keep the height of the dot placement in capital letters consistent, and the ascender in B is relatively short.

**Comment by psb1558** [comment]
Interesting. I think the position of the dot on the cap in Ríchló GC is likely to be a stylistic choice—what looked good to the designer. It can't be to keep the position of the dot consistent across caps: assuming that the height of the B is the same as that of the other caps, the dot on the B is centered on the cap-height, where it couldn't be for, say, C:
<img width="142" alt="image" src="https://user-images.githubusercontent.com/16215767/233981444-5c044dbd-f8c9-440e-8137-429ec6fb859c.png">
I don't know what the takeaway is here. It seems to me, so far, that the position of the dot on the B is up to the designer.

**Comment by silmeth** [comment]
![Ríchló ḂĊḊḞĠṀṖṠṪ](https://user-images.githubusercontent.com/5329644/233983486-22e2c54e-4460-49a5-a614-3851677d122d.png)

B and D are higher in this font, the dot is consistently kept on the same height.

**Comment by silmeth** [comment]
And at first glance seems to be similar in the original Petrie too. Although here the B is lower and C is taller (C touching the dot, B having a gap).

![Petrie: Ċaroluis, Ḃearaḃu…](https://user-images.githubusercontent.com/5329644/233984554-ccf6fcfc-4e09-434b-8a5f-e2a3f3fbf404.png)

**Comment by psb1558** [comment]
Hmm. I should have followed your link to the font before pontificating. Perhaps it would be better, after all, to keep the dot at the same position as on the other caps. The effect will be better in running type.

I did put the dot on the b at the location that's standard for i, j, etc.

**Comment by silmeth** [comment]
And here’s an example of an older version of Petrie that has capital B similar to the one in Ríchló (but I don’t think the book uses dots over capitals, rather writing GH, BH, etc. instead, so no example of dot placement): https://archive.org/details/annalarioghachta01ocleuoft/page/12/mode/2up

![obraz](https://user-images.githubusercontent.com/5329644/233988534-7485068c-0567-4aa9-b473-e09d755625a8.png)

**Comment by psb1558** [comment]
This is done in version 1.058 (now in the repository).
