### ISSUE TITLE
Add Commas and Dashes to Sub- and Superscripts

### ISSUE THREAD

**Issue by amarakon** [psb1558/Junicode-font#172]
Commas and dashes are used in superscripts to mark multiple footnotes. They might also be used in subscripts. Can you add them to the `sups` and `subs` features?

![new-1](https://user-images.githubusercontent.com/92645199/233858312-dddf9eaf-462f-4f8a-9d45-d7353cd9d75e.png)

**Comment by psb1558** [comment]
Good idea. I'll do this.

**Comment by psb1558** [comment]
I've added superscript hyphen, endash, period, comma. They'll be in the next build, probably later today.

I haven't added to subscripts yet. I'd like to know that someone will actual use those characters in subscript.

**Comment by psb1558** [comment]
I think this is done.
