### ISSUE TITLE
Option to Enable Only Uppercase Swash Letters

### ISSUE THREAD

**Issue by amarakon** [psb1558/Junicode-font#173]
I like swash letters for uppercase italics, but not for lowercase letters. Can you add an option so that when `swsh` is enabled, only uppercase letters like ‘A’ have swashes, but not lowercase letters like ‘r’.

![new-1](https://user-images.githubusercontent.com/92645199/233858938-5e10cac6-ae32-4c0e-9144-384c5e5e374a.png)

**Comment by psb1558** [comment]
Those lowercase letters aren't really swashes and don't belong in the swsh feature. As there are better ways to access them now, I'll remove them.
