### ISSUE TITLE
Restore the Original Top Half Brackets

### ISSUE THREAD

**Issue by amarakon** [psb1558/Junicode-font#174]
Can you restore Junicode’s top half brackets (`U+2E22` and `U+2E34`)? They look way better when they are less than half the height of regular brackets. If not, can you at least add a character variant or stylistic set so users can restore it themselves?

![import-2023-04-23_15:41:11](https://user-images.githubusercontent.com/92645199/233861528-ca63e59c-4123-42b9-8e3a-9f695518789c.png)

**Comment by psb1558** [comment]
Honestly, I'm not sure why I changed these. I agree that the earlier form was better.
