### ISSUE TITLE
Previous version

### ISSUE THREAD

**Issue by apikshafiee** [psb1558/Junicode-font#176]
Hi and thank you very much for your efforts.

Is it possible to archive the previous version(s), please?

I wrote something with the previous one which had a different line spacing and now all the lines are close to each other by the newest version.

Thanks a lot
Yours

**Comment by psb1558** [comment]
You can get anything you want from the repository history.
But I do agree that the default line spacing is too tight right now. I've increased it by about 25%, and that change will be reflected in the next versions I post.
I've mentioned this several times, but I'll repeat: there's a good bit of disagreement about how the various vertical metrics settings should work, and different fonts handle the problem in a number of different ways. There's no standard. I think it is usually best to ignore the font's vertical metrics and set the line spacing explicitly in the word processor, LaTeX file, or whatever.

**Comment by apikshafiee** [comment]
Thank you very much. I really appreciate your efforts on this high professional and useful font.

Yours
Apik

**Comment by psb1558** [comment]
I guess this is as finished as it's going to be.
