### ISSUE TITLE
Code Page "Win-1254" information is missing in Junicode Beta 1.8.4

### ISSUE THREAD

**Issue by dawidd4** [psb1558/Junicode-font#182]
Although the font supports Turkish characters like Ş and Ç, some programs don't detect the Win-1254 code page, because the information is missing in Junicode Beta. (This issue does not apply to Junicode 1.003)
... But if I look closer, there are many other code pages that are missing in the Font properties, such as Win-1253 or Win-1255

**Comment by psb1558** [comment]
Adding a "code pages" property in Glyphs causes fontmake to crash. I'll look into adding this information some other way.

**Comment by psb1558** [comment]
I'll be using a little Python script. Will include it in the toolchain starting with the next build, but in the meantime I thought I'd post it here for comment:
```
from fontTools import ttLib
import sys

# 0:  1252 Latin 1
# 1:  1250 Latin 2
# 3:  1253 Greek
# 4:  1254 Turkish
# 7:  1257 Windows Baltic
# 8:  1258 Vietnamese
# 29:      Macintosh character set
# 31:      Symbol character set
# 32-63:   DOS code pages not used
#       31  27  23  19  15  11  7   3
cp1 = 0b10100000000000000000000110011011
#       63  59  55  51  47  43  39  35
cp2 = 0b00000000000000000000000000000000

if __name__ == "__main__":
    if len(sys.argv) > 1:
        for i, f_name in enumerate(sys.argv):
            if i > 0:
                print("Fixing " + f_name)
                ft_font = ttLib.TTFont(f_name)
                ft_font["OS/2"].ulCodePageRange1 = cp1
                ft_font["OS/2"].ulCodePageRange2 = cp2
                ft_font.save(f_name, 1)
```
I could include relevant DOS code pages, but I'm not sure there's a lot of point. The fonts I've checked leave ulCodePageRange2 all zeros.
