### ISSUE TITLE
Punctus elevatus

### ISSUE THREAD

**Issue by lguariento** [psb1558/Junicode-font#186]
Hello, I've installed the fonts on my MacOS; I'm looking for the punctus elevatus. Is this available? I cannot see in the font definitions. Am I missing something? The Arab one gets very close to it (U+F1F0). I'm looking for 2e4e though. Is this available?

**Comment by lguariento** [comment]
> It's U+2E4E. Use this code point instead of the MUFI 4.0 U+F161 (the MUFI code point will certainly be retired, if it hasn't been already, now that _punctus elevatus_ is part of the Unicode standard). There are variant shapes on cv74: see the current Junicode Manual, p. 26. For finding things in Junicode, you should also get the [MUFI 4.0 reference](https://folk.uib.no/hnooh/mufi/specs/MUFI-Alphabetic-4-0.pdf).

Thank you for your reply. I'm afraid I don't seem to have 2E4E. Am I missing something? I installed version 1.0003, TTF inside the `legacy` folder.

**Comment by psb1558** [comment]
Oh, okay. U+2E4E is too recent to be in Junicode 1 (which is no longer receiving additions). Either switch to Junicode 2 or use U+F161.
