### ISSUE TITLE
Interpolation Issues v1.061 Roman #2 - pcap diacritics height

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#189]
Interpolation Issues v1.061 Roman 2 - pcap diacritics height

File: JunicodeTwoBetaVF-Roman.ttf, v1.061 beta, 2023-07-10

Glyphs: /hcaron.pcap/hcircumflex.pcap/hdieresis.pcap/hdot.pcap/nacute.pcap/ncaron.pcap/ndot.pcap/ngrave.pcap/ntilde.pcap

Some of the pcap diacritics move with the Enlarge axis (like they are still lowercase).

![2023-07-12_19-08-16](https://github.com/psb1558/Junicode-font/assets/844920/63106b7e-60b5-4c28-92be-7e46a32155d0)

p.s. forgot about the real pcaps - love them.

**Comment by psb1558** [comment]
Bad anchors on U+0274 and U+029C. I have fixed them.

Thanks again!

**Comment by kenmcd** [comment]
The vertical height fix looks good for all for them.
But now I noticed the `grave` on the `/ngrave.pcap` is shifting left-and-right with the Enlarge axis.

**Comment by kenmcd** [comment]
> I noticed the `grave` on the `/ngrave.pcap` is shifting left-and-right with the Enlarge axis.

Looks like it is the anchors on the /ngrave.pcap,
Appears the /gravecomb is fine - it does not move by itself.

![2023-07-24_19-01-09 ngrave pcap](https://github.com/psb1558/Junicode-font/assets/844920/adcb6ed8-292e-49cd-a082-8ade26e17965)

**Comment by psb1558** [comment]
I believe these have all been addressed (tested just now). Close if you agree.

**Comment by kenmcd** [comment]
No.  
Roman v1.069 /ngrave.pcap still has a moving grave like the GIF above.
/ngrave.pcap
01F9.pcap
glyph# 1544

**Comment by psb1558** [comment]
Hmm. I thought it was a simple problem, but it's not. I haven't yet figured out what's going on: it may take some time.

**Comment by kenmcd** [comment]
Checked /ngrave.pcap in v2.000beta4 - and looks like you fixed it.
Closing this now.
