### ISSUE TITLE
Interpolation Issues v1.061 Italic #1 - various

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#192]
Interpolation Issues v1.061 Italic 1 - various

File: JunicodeTwoBetaVF-Italic.ttf, v1.061 beta, 2023-07-10

Glyphs: /Astroke/Aogonek.alt2/eth/thornstroke/astroke.sc/aogonek.alt2.sc/uF001E/iturnedmod/closeup/undertie/parenright.inferior/parenright.superior/dieresis

/Astroke/Aogonek.alt2/astroke.sc/aogonek.alt2.sc/uF001E
The stroke angle is almost vertical at min width and max weight.
![2023-07-13_15-33-26-Astroke-issues](https://github.com/psb1558/Junicode-font/assets/844920/4722ef0c-40ad-4155-aa58-f09205f8eced)

/eth/thornstroke
The stoke gets kinda mushed (technical term) at min Width, max Weight, and max Enlarge
![2023-07-13_15-37-04-eth-thornstroke](https://github.com/psb1558/Junicode-font/assets/844920/6c92ed37-8a72-47ca-b47c-695b1e664ade)

/undertie
Same issue as in the Roman - at min Weight and max Width parts disappear
![2023-07-13_15-44-05-undertie](https://github.com/psb1558/Junicode-font/assets/844920/1c82e861-259f-47ff-bd0e-27c71e8e96d5)

/iturnedmod/closeup/parenright.inferior/parenright.superior
Appear to be different start point issues - and element order on /closeup
![2023-07-13_15-48-46-start-point-issues](https://github.com/psb1558/Junicode-font/assets/844920/cecd3b19-e098-47b0-b839-948426556c64)

/dieresis
Not sure what is going on with the width there.
![2023-07-13_15-55-52-dieresis](https://github.com/psb1558/Junicode-font/assets/844920/561814da-ca32-44cd-9877-e170d031da47)

You may also want to take a look at the `.case` diacritics.
Something similar happening with them with the width.

**Comment by kenmcd** [comment]
Checked Italic v1.064 - and it appears these are all still open.

**Comment by psb1558** [comment]
Two experiments re: Astroke. First, keeping the angle of the stroke constant. Here collisions are unavoidable, though only at extremes:
![Screen_Recording_2023-07-22_at_3_17_54_PM_AdobeExpress](https://github.com/psb1558/Junicode-font/assets/16215767/d5b37594-deda-40ec-b724-df24585e54e7)
Second, nailing the stroke to fixed points on the baseline and the right-hand stem of the A. With this method, the angle of the stroke changes as the axes change. I thought there would be fewer collisions, but perhaps not:
![Screen_Recording_2023-07-22_at_3_43_16_PM_AdobeExpress](https://github.com/psb1558/Junicode-font/assets/16215767/281c88e1-4a26-45dd-b488-679641faf716)
It seems that collisions are unavoidable with this glyph (and, presumably, others like it).

Do you have a preference?

**Comment by psb1558** [comment]
This one fixes an awkwardness in method 2 at min width/max weight by nudging the bottom of the stroke a little left. It also fixes the stroke length so height and depth are always the same.
![Screen_Recording_2023-07-22_at_4_15_30_PM_AdobeExpress](https://github.com/psb1558/Junicode-font/assets/16215767/2a8e0683-cc87-46b2-9e12-cc0f3e546b66)

**Comment by psb1558** [comment]
Bad that I missed those. But they're fixed now.
