### ISSUE TITLE
v1.061 beta - figuredash issues

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#193]
There are issues with the /figuredash (U+2012) in both the Roman and the Italic.

The default figures are tabular and are 467 wide at 100 width.
This is the same in both the Roman and Italic.

In the Roman: 
The figuredash advance width remains at 500 no matter the width axis setting. No advance width interpolation occurs.
So the glyph sticks out of the box at higher width axis settings, and at lower widths, since the AW stays at 500, it looks odd as a short glyph in a too wide box.
But in the Roman the vertical thickness does vary with the weight axis setting. So the weight interpolation appears to be working in Roman.

In the Italic: 
The figuredash advance width is 467 at 100 width as it should be, and the width axis interpolates properly.
But changing the weight axis does not affect the thickness, it also only affects the width. Which is quite odd.
So the weight interpolation does not appear to be working properly in Italic.

/figuredash needs some love in both Roman and Italic.

**Comment by psb1558** [comment]
Fixed.

**Comment by kenmcd** [comment]
Checked v1.064 beta

Romain and Italic - Width axis - now appears to work for both

Roman - Weight axis appears to be the same - working.

Italic - Weight axis does not appear to do anything.
Definitely better that it no longer affects the width, but shouldn't it thicken the glyph the same as the Roman?
