### ISSUE TITLE
v1.061 beta - figurespace issues

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#194]
The /figurespace (U+2007) has issues in both the Roman and Italic.

Like the default tabular figures, the figurespace has a width of 467 at Width axis 100.
In both the Roman and Italic.

When increasing the Weight axis to the max of 700, the width drops to 466.
So the Bold masters in both Roman and Italic probably need this changed to 467.
Dropping the Weight axis to the min of 300, they both remain at 467.
So the Light masters appear to be OK.

The Width axis is where it gets really weird (in the Italic).

Roman
Width 100 (default) = 467
Width 75 (min) = 384
Width 125 (max) = 549

Italic
Width 100 (default) = 467
Width 75 (min) = 374  (?)
Width 125 (max) = **293**  (???)

Obviously the Italic max Width axis figurespace width should be higher.
And I think the Roman and Italic min and max widths should be the same - so italics will also line-up in a table of tabular figures.

I did not check these widths against the actual tabular figures at the same min and max Width axis settings, but they should also be the same.

**Comment by psb1558** [comment]
Thanks for all these good things.  Better that I should spend my time fixing stuff than post replies and progress reports. I'll close them as appropriate (the figurespaces, for example, are fixed now).
