### ISSUE TITLE
v1.064 beta - endash emdash horizontalbar

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#196]
v1.064 beta - endash emdash horizontalbar

**/endash/emdash/horizontalbar**

In the **Roman** these appear work as expected with the 3 axes.
Weight axis interpolates as expected.
Width axis interpolates as expected.
Enlarge axis has no effect, as expected.

![2023-07-15_14-26-47-Roman](https://github.com/psb1558/Junicode-font/assets/844920/740a2feb-6df9-471f-a14b-763a948a4766)

But, in the **Italic** there are some unexpected results.
Weight axis changes the _width_ of the horizontalbar, and _not_ the weight.
Width axis does _not_ change the width of the emdash.
Enlarge axis shifts all three, and changes the width of the horizontalbar.

![2023-07-15_14-29-58-Italic](https://github.com/psb1558/Junicode-font/assets/844920/2079bc06-90c1-411c-94ea-58189caf5fe5)

**Comment by psb1558** [comment]
I think these are all fixed in 1.067: try it out and see if it works properly for you.

**Comment by kenmcd** [comment]
Looks good in v1.067. Closing this.
