### ISSUE TITLE
Some issues with turned letters and combining diacritics

### ISSUE THREAD

**Issue by ischaap** [psb1558/Junicode-font#197]
Dear Dr Baker,

Thank you very much for your work on this beautiful font. I've been doing some testing with the medium-weight TrueType version in MS Word and I noticed some issues with anchor points for various turned letters. Some look correct:

![image](https://github.com/psb1558/Junicode-font/assets/139657890/5e5ae7c3-064e-486e-ad65-f07dc749edcf)

But some need repositioning:

![image](https://github.com/psb1558/Junicode-font/assets/139657890/9baa6d5a-e02e-4a06-ac41-a7d15524080f)

While the IPA letter chi of course isn't turned, it too needs adjusting:

![image](https://github.com/psb1558/Junicode-font/assets/139657890/a7c565b6-ca50-43e9-8a93-0eb607fda00c)

Finally, it seems to me that, compared to their combining counterparts, the modifer uptack, downtack, plus and minus signs are too large. The modifier minus sign also has some unexpected serifs on it:

![image](https://github.com/psb1558/Junicode-font/assets/139657890/1f222aa1-875b-42f2-b783-ce0d8bb6e0bc)

I hope this feedback is helpful. Thanks again for all you do!

**Comment by psb1558** [comment]
I'll add anchors to these.

**Comment by ischaap** [comment]
Thank you! I'm afraid wasn't exhaustive in fiding these, and taking another look it seems that other IPA letters need anchors placed or adjusted as well, for example (again probably not exhaustive, unfortunately):

LATIN SMALL LETTER N WITH RETROFLEX HOOK U+0273
LATIN SMALL LETTER N WITH LEFT HOOK U+0272
LATIN SMALL LETTER DOTLESS J WITH STROKE U+025F
LATIN SMALL LETTER Q U+0071
GREEK SMALL LETTER THETA U+03B8
LATIN SMALL LETTER PHI U+0278
LATIN SMALL LETTER C WITH CEDILLA U+00E7
LATIN SMALL LETTER J WITH CROSSED-TAIL U+029D
LATIN LETTER GLOTTAL STOP U+0294
LATIN LETTER PHARYNGEAL VOICED FRICATIVE U+0295
LATIN SMALL LETTER R WITH TAIL U+027D
LATIN LETTER GLOTTAL STOP WITH STROKE U+02A1
LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE U+02A2
LATIN SMALL LETTER L WITH RETROFLEX HOOK U+026D
LATIN SMALL LETTER TURNED R WITH LONG LEG U+027A
LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK U+0284
LATIN SMALL LETTER B WITH HOOK U+0253
LATIN SMALL LETTER G WITH HOOK U+0260

![image](https://github.com/psb1558/Junicode-font/assets/139657890/198f5794-0eef-436a-87ac-10fccdf70230)

Also, regarding r-shaped letters, I wonder if would preferable to have the anchors centred on the stem? Right now they seem to be centred on the overall width.

![image](https://github.com/psb1558/Junicode-font/assets/139657890/1882f5fe-a98d-47a4-98c4-17fbda26b566)

**Comment by psb1558** [comment]
I've done these things:

- added/corrected anchors in all glyphs in the Unicode IPA Extensions range;
- fixed the modifiers U+02D4—U+02D7;
- corrected poor outlines and faulty interpolations, especially in the roman face.

I have posted only static TrueType and variable TrueType versions (version 1.066); please test and let me know if anything seems wrong or is still missing.

**Comment by ischaap** [comment]
Thank you! Of the examples I posted, all look much better now except for two which still need attention:

GREEK SMALL LETTER THETA U+03B8
LATIN SMALL LETTER C WITH CEDILLA U+00E7
![image](https://github.com/psb1558/Junicode-font/assets/139657890/4427b5c7-79fc-456e-8440-66ebf8892aba)

On some of the other glyphs I'd given as examples, the bottom anchors now look correct, but top anchors still seem misplaced (diacritics chosen at random):

LATIN LETTER GLOTTAL STOP U+0294
LATIN LETTER PHARYNGEAL VOICED FRICATIVE U+0295
LATIN LETTER GLOTTAL STOP WITH STROKE U+02A1
LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE U+02A2
LATIN SMALL LETTER L WITH RETROFLEX HOOK U+026D
LATIN SMALL LETTER L WITH RETROFLEX HOOK U+026D
LATIN SMALL LETTER B WITH HOOK U+0253
LATIN SMALL LETTER G WITH HOOK U+0260
![image](https://github.com/psb1558/Junicode-font/assets/139657890/5f2b41b3-5b8d-45e9-80f7-9b99055236ca)

And a couple others that I discovered just now on checking some more glyphs:

LATIN SMALL LETTER D WITH TAIL U+0256
LATIN SMALL LETTER J WITH CROSSED-TAIL U+029D
![image](https://github.com/psb1558/Junicode-font/assets/139657890/9ffd181f-40fc-4273-903b-295abd645c03)

**Comment by psb1558** [comment]
I missed the theta and ccedilla because they're not in the IPA range. I will fix.

About the others: I was following the usage of the Brill font, which does not have anchors in the places you indicate. Since Brill is very authoritative, I thought this meant that combining marks didn't appear in those places. I noticed especially that Brill (almost) never places a top anchor on an IPA character with hook above. Do you yourself need combining marks in those places, or are you checking for completeness? I'm glad to supply them if needed, but I don't want to put in stuff (in an already crowded font) that will get no use.

**Comment by ischaap** [comment]
I was really just checking for completeness. I guess I had in mind a font like Calibri for example, which has anchors for almost any situation, but I agree Brill is authoritative and the examples I posted were very much corner cases or even hypotheticals. I personally wouldn't need to use these.

**Comment by psb1558** [comment]
Junicode has specialized anchors for attaching medieval abbreviations, etc., so it's already bursting at the seams, with an overflowing GPOS table. So I'm trying to be fairly severe about what I put in. It was a good project to add anchors for IPA characters, since these will definitely be used—but I do want evidence of use.

**Comment by psb1558** [comment]
Anchors for theta and ccedilla are in v. 1.067, just posted.

**Comment by ischaap** [comment]
Thank you  @psb1558 for this, and for being so responsive! Unfortunately, I'm still seeing problems with these. C-cedilla could be used to transcribe a retracted voicless palatal fricative, but the retraction sign doesn't fit underneath. The bottom anchor for theta works, but only for the Greek shape, not the IPA shape (stylistic set 3):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/e8d4754f-e712-454a-a7ea-59bcf4d82e9d)

Granted the c-cedilla issue may not be critical since you could also use [x̟] or [ç˗].

**Comment by psb1558** [comment]
Hmm. I don't know what was wrong with ccedilla, but I've manage to fix it anyway. The alt theta was an oversight, now fixed. Look for it in 1.068.

**Comment by psb1558** [comment]
I think this is done now. Reopen if you need to add anything.
