### ISSUE TITLE
cyrillic small letter soft / hard sign: U+044C / U+044A

### ISSUE THREAD

**Issue by suetzjoh** [psb1558/Junicode-font#198]
I would like to request the inclusion of the letters ъ and ь on behalf of the Old Lithuanian Etymological Dictionary project at Humboldt-University Berlin (https://alew.hu-berlin.de). We currently lack a Unicode font that contains all the special characters that are needed for Lithuanian philology, ṡuch as * l̃, ę́, ė̃ or ė́*. Junicode contains almost all of those characters, except for ъ and ь.

U+044A CYRILLIC SMALL LETTER HARD SIGN
U+044C CYRILLIC SMALL LETTER SOFT SIGN

In Slavic historical linguistics, reconstructions of words are usually written with latin characters, but the cyrillic letters ъ and ь are used for the Proto-Slavic sounds that historically derive from Proto-Indo-European short /u/ and /i/ respectively. Thus the community of Slavic philology would also greatly benefit from this inclusion.
______

Note: I already voiced this request on sourceforge a while back, so this might technically be a duplicate.

**Comment by psb1558** [comment]
I'll be glad to add these, and will close this when they're done. A question: are there ever diacritics either above or below these letters?

**Comment by suetzjoh** [comment]
Thank you very much!

Yes, they sometimes have accents. I’ve seen ъ́, ь́, ъ̏, ь̏, ъ̀, ь̀ and I can also imagine ъ̍, ь̍ to be useful.

**Comment by psb1558** [comment]
Okay. These will have anchors so that you can position any combining marks over them, and they will be positioned correctly.

**Comment by ischaap** [comment]
I'm really happy to see these added. I think the placement of the grave diacritics could be adjusted a bit though, and I'm also wondering if a more italic shape could be made for the italic glyph. See below with Brill for comparison (v. 1.066 static TTF medium weight in MS Word):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/348636be-036b-45f4-afc3-5e3a04336a86)

**Comment by psb1558** [comment]
I'll have a look.

**Comment by ischaap** [comment]
@psb1558 I wonder if, when you're able to revisit these, you could also add `U+042A` capital hard sign, `U+042C` capital soft sign, and small caps and petite caps for both -- would be most appreciated.

**Comment by suetzjoh** [comment]
@silmeth 'ъr' is a so-called ‘mixed diphthong’ which have the same tonal distinctions as the long monophthongs. Cf. the corresponding (Old) Lithuanian word _gurdùs_, A.sg. _gur̃dų_ with circumflex as apposed to e.g. [_kùrti_](https://en.wiktionary.org/wiki/kurti#Lithuanian) with acute. The notation for the acute can be seen in [_*pь̀lnъ_](https://en.wiktionary.org/wiki/Reconstruction:Proto-Slavic/p%D1%8Cln%D1%8A).

**Comment by psb1558** [comment]
For comment, here are new italic forms.
<img width="450" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/46425cdf-8360-4588-ad28-54c50c5c9126">
I don't have a feel for cyrillic, so feedback would be very welcome.

**Comment by psb1558** [comment]
This is done. The changes/additions will be in the next release (probably in a week or so).
