### ISSUE TITLE
Kerning of inverted commas/quotation marks

### ISSUE THREAD

**Issue by ischaap** [psb1558/Junicode-font#199]
The kerning of inverted commas/quotation marks seems pretty tight, perhaps a little too tight when words begin with _i_ or _j_.

Junicode Two Beta (medium weight):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/ffad58f2-6488-4a7e-9b99-fdec3b64e49a)
![image](https://github.com/psb1558/Junicode-font/assets/139657890/e1afce32-bafa-4980-8a59-4d79397a1c93)

Junicode One for comparison:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/991af0ce-465b-49a9-90df-ace720f07118)
![image](https://github.com/psb1558/Junicode-font/assets/139657890/b921082e-8856-4b2e-99b9-0a10c1183f61)

Here are words ending in _i_ and _j_ (just single quotation marks to illustrate this time):

Junicode Two Beta (medium weight):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/485bab0a-e783-4c3b-89ca-9037a0ba334a)

Junicode One:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/3bb6a33a-7967-4c55-8f81-f2aed291ea85)

To my eye at least, the Junicode One kerning is preferable -- maybe this could be restored?

**Comment by psb1558** [comment]
Yes. I'll loosen up this spacing.

**Comment by ischaap** [comment]
Glad it's helpful! I have a number of documents that I can test with, so I'll keep my eyes open.
