### ISSUE TITLE
v. 1.066 kerning pairs

### ISSUE THREAD

**Issue by ischaap** [psb1558/Junicode-font#202]
I'm testing v. 1.066 in medium weight using the static TrueType version in MS Word. I've come across a few more kerning pairs that could use some touching up. (These are all in documents that I would eventually like to set in Junicode Two for print.)

A gap between capital O and g:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/d1932e61-1a00-456b-89d5-0931ffb95260)

SOLIDUS U+002F aka 'forward slash' is too close to MODIFIER LETTER VERTICAL LINE U+02C8, and this is a combination that will be used very often in phonemic trancriptions. 
![image](https://github.com/psb1558/Junicode-font/assets/139657890/8358cd02-21b8-4273-a51a-5aa4039310e0)

In a non-transcription context, solidus is also too close to iota with breathing diacritics:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/73929fcd-779c-420d-ae64-4c1db33869cd)

Back to a transcription context, LATIN SMALL LETTER TURNED ALPHA U+0252 needs a little more space when it follows glyphs with right-reaching strokes:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/abe1e7a8-1753-4b3f-bb3e-82d6cee2d739)

Round, square, and curly brackets are little too loose around LATIN SMALL LETTER SCHWA U+0259, but are fine around LATIN SMALL LETTER TURNED E U+01DD (angle brackets look okay to me):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/b0bfa71e-5f4b-4d70-9beb-d4e79a6ea78e)

However, angled brackets need adjustment with glyphs with tails or hooks -- important in illustrating orthographies. Some examples:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/f7c6ec11-d583-4138-aabd-c4431c9433c5)

In the combination f + ï (as sometimes in orthography for Old French), it looks like the short or narrow f is being correctly applied, but it still doesn't quite fit:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/02a07815-79bd-4c1e-adfd-5e816c946048)

I'm not sure what could be done about that one -- more spacing? Or maybe a special ligature as below? (forgive the crudeness)
![image](https://github.com/psb1558/Junicode-font/assets/139657890/9ef6420b-481d-45f5-98c7-7926d0d52dce)

**Comment by psb1558** [comment]
Various issues here. Some rogue kerning (I'm reviewing kerning pairs, trying to root out the rogues, but there are more than 5,000; it will take some time). Some metrics gone bad (this is disturbing: I have no idea how it happened); some new kerning needed. I've just posted version 1.067, with many fixes to metrics and kerning. Try it out and let me know what else is needed!

**Comment by ischaap** [comment]
Things are looking good in v. 1.067. Thanks so much for making all these tweaks. I did come across a few more spacing odds and ends:

Small cap J (achieved in Word using U+1D0A) colliding with round brackets:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/42527073-08d7-43de-981e-539d099eaca4)

Some italic lowercases are a bit tight with roman closing quotation marks:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/402fa2d0-dee6-4af4-8eda-a229b8cc69bd)

Various italic upper- and lowercases colliding on the left or right with square and round brackets:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/8f5394d9-cb54-4919-8d72-422c7a273e71)

Couple of IPA glyphs colliding with square brackets (possibly there are more but I happened to come across these in test documents):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/90abdace-48f9-47d7-b6f4-a527b11cb581)

The sequence bb seems to have a little extra spacing (cf. dd):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/390eb8e4-f712-4e57-858b-5f2b14d56d6f)

And finally, I'm wondering about the kerning of italic closing quotation mark/apostrophe with a following letter. In some combinations it looks fine to me (e.g. _I'll_, _Arthur's_), but in others (e.g. _fin'amor_, _Andy's_, _you'd_) it looks pretty tight.
![image](https://github.com/psb1558/Junicode-font/assets/139657890/f48bc68b-c81f-48c2-bb0c-3a12aba56d90)

**Comment by psb1558** [comment]
U+1D0A is a petite cap. No matter—I have fixed the collision of pcap **j** with all left brackets, the collision of pcap **q** with all right brackets, and all italic collisions with bracket characters.

The metrics of **b** had somehow gotten thrown off, and I have fixed. Also added contextual kerning for **n’a** and **u’d**.

Can't kern an italic with a following roman character, since they are in different fonts. Those have got to be fixed up in the document.

I think we have addressed all these things now.

**Comment by ischaap** [comment]
Looking at this again, it doesn't look the the spacing for italic closing quotation mark/apostrophe has been adjusted in v. 2.000beta3.

It's especially noticeable in italic when the italic quotation mark or apostrophe follows a letter with a diactric.

![image](https://github.com/psb1558/Junicode-font/assets/139657890/f60228e7-1c38-411b-8499-06f7b67d89d4)

I think the spacing of quotation marks/apostrophes in italic may be a little too tight overall, and it's quite noticeable in the context of apostrophes. Some random examples in Junicode, Minion 3, and Brill. The spacing in Brill is similar to that in Junicode, in that very little space follows the apostrophe, but Junicode's quotation mark/apostrophe is more like Minion 3's in terms of its shape and scale. I do think that of the three, Minion 3's spacing looks the most successful and easy to read.

![image](https://github.com/psb1558/Junicode-font/assets/139657890/326a81a5-633e-48e0-84cf-76da5efe2615)

**Comment by psb1558** [comment]
I'll review the metrics and spacing of apostrophe and quotation marks. I can't promise to make every possible sequence of letter + apostrophe + letter look right—with any font (including some of the sequences in Brill), users will sometimes have to kern manually. But I'll do what I can.

**Comment by psb1558** [comment]
I've been over the kerning pairs involving the quoteright/apostrophe, the kerning for which was way too tight. I've made other adjustments to italic kerning as well. Again, it is not possible to tend to every possible kerning pair, but the general appearance of documents should be better now.

The result so far is in 2.000beta4.

**Comment by ischaap** [comment]
Great improvement, thank you!
