### ISSUE TITLE
v. 1.066 anchors for glyphs with macrons

### ISSUE THREAD

**Issue by ischaap** [psb1558/Junicode-font#203]
Again testing in v. 1.066 static TTF in MS Word at medium weight.

Glyphs with macrons don't seem to have the correct anchors -- the macron is correctly position but additional diacritics above and below are not correct. I tried in various combinations with COMBINING ACUTE ACCENT U+0301, COMBINING BREVE U+0306, and COMBINING DOT BELOW U+0323. These would be important in orthography for Middle English, Latin, romanized Ancient Greek, possibly others. (But note e with macron and acute and o with macron and acute are working):
![image](https://github.com/psb1558/Junicode-font/assets/139657890/a01758c2-086d-4631-a4d1-46321cdff915)

I can't be sure now but I had the impression the above were all working correctly in v. 1.064.

Related, it would be nice if Greek glyphs with macrons could accept diacritics:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/dc35676c-3948-4c79-894e-b48501ac4bb5)

**Comment by psb1558** [comment]
Sorry—I was experimenting with a setting in my build script, and it obviously didn't work out. I will put it back the way it was, and it will work properly next time I post fresh fonts:
<img width="393" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/e8250713-8004-489a-8539-b70d200484dc">
However, sometimes diacritics will be badly positioned over other diacritics even so, for technical reasons that I will explain only if asked. But when this happens, place a Combining Grapheme Joiner (U+034F) between the base character and the first diacritic. That character is an invisible zero-width combining mark that was included in Unicode for precisely this purpose, and it will fix the problem almost every time.

**Comment by psb1558** [comment]
This fix is in v. 1.067, just now uploaded. Try it out and let me know how it works!

**Comment by ischaap** [comment]
Looks terrific, much appreciated! Thanks too for the tip about U+034F. Before switching my Junicode Two v. 1.066 installation to v. 1.067 I tried it out but actually couldn't get it to work in Word (probably not surprising). Nevertheless I'll remember it for use in InDesign.

**Comment by psb1558** [comment]
It ought to work with Word (I'll see if I can get access to Word so I can test). There are a couple of mentions of U+034F in the Junicode Manual, and examples of where it is needed.

**Comment by psb1558** [comment]
I think we can call this fixed, and close.
