### ISSUE TITLE
V. 1.067 k with acute

### ISSUE THREAD

**Issue by ischaap** [psb1558/Junicode-font#206]
One last item for today! To my eye the position of the diacritic in lowercase k with acute (used by Indo-Europeanists) looks like it could perhaps be raised ever so slightly:
![image](https://github.com/psb1558/Junicode-font/assets/139657890/ffca364f-cfb9-4fbe-a99a-7fcd750bc988)

**Comment by psb1558** [comment]
This is fixed and will be in the next build.
