### ISSUE TITLE
1.067 Light spacing

### ISSUE THREAD

**Issue by marrus-sh** [psb1558/Junicode-font#208]
I noticed when playing around with numbers that the size of the space seems slightly larger in the Light weight (both Roman and Italic) than in Regular or Bold. It’s pretty subtle, but…

![image](https://github.com/psb1558/Junicode-font/assets/3212430/31ceaa49-d413-45a7-93d8-768a36cff808)

You can see that the Light digits `34` have shifted to the right instead of being centred in the corresponding box of the Bold. Regular might also be shifted a little to the left, but it looks a lot closer. (To be clear, the issue here is the space not the numbers; the same difference is perceptible with e.g an emdash.)

I don’t have a stance on whether the spacing actually *should* be the same in all three weights, but it seemed surprising to me that Light would be the widest of the three, and fairly noticeably—so I wanted to call it out in case it was not intentional.

(Screenshots taken from TextEdit using the variable version of the font.)

**Comment by psb1558** [comment]
Thanks, kibigo!!

The sidebearings of light glyphs are a little wider than for regular (and bold sidebearings are narrower) to balance the larger (or smaller) amount of whitespace inside the glyphs. This is pretty standard practice.

But I don't know if the spaces should be wider or narrower to match. I'll investigate other fonts with a width axis and see if there's a standard usage here.

**Comment by psb1558** [comment]
A very interesting early return:

Roboto Flex (sans) keeps the width of the space constant as the width axis changes. Roboto Serif (both roman and italic) vary the width from 200 font units (when wdth=50) to 298 (when wdth=150).

I'll go on looking.

**Comment by psb1558** [comment]
I surveyed a very small collection of fonts: Brill (static), Garamond Premier Pro (static), Roboto Serif (variable), NotoSerifDisplay (variable).

Brill and GaramondPP both have a narrower space in bold than in regular; the two variable fonts, on the other hand, keep the width constant. A variable-width space makes sense to me from a design perspective, but I wonder if the two multi-axis variable fonts are keeping the space constant to avoid complication. What I need to do, I think, is experiment and try to decide what looks best.

**Comment by psb1558** [comment]
Here is a PDF (made with LuaTex) reflecting the current spacing. I'll do one with the spacing more variable, and one with the spacing fixed. Comments welcome. 
[JunicodeSpacingTest-1.pdf](https://github.com/psb1558/Junicode-font/files/12164655/JunicodeSpacingTest-1.pdf)

**Comment by psb1558** [comment]
In #2 the spacing is widest in the Light face, and narrowest in Bold, with the other faces in between, and in #3 the spacing is the same in all faces.
[JunicodeSpacingTest-2.pdf](https://github.com/psb1558/Junicode-font/files/12164842/JunicodeSpacingTest-2.pdf)
[JunicodeSpacingTest-3.pdf](https://github.com/psb1558/Junicode-font/files/12165058/JunicodeSpacingTest-3.pdf)
Which looks best?

**Comment by psb1558** [comment]
My vote is for #3.

**Comment by marrus-sh** [comment]
the differences might be more noticeable if you make it `\raggedright`?

in any case, i would defer to your judgement, with the possible thought that if there isn’t a strong feeling one way or the other to just go with the one which is conceptually simpler (keeping them all the same)

i also wonder to what extent other kinds of spaces (thin space / narrow no‐break space / etc) should vary between weights, and keeping them the same might be desirable just so there is less to keep track of.

**Comment by psb1558** [comment]
I should have thought of making them `\raggedright`.

But I think, in a font that is (sometimes) variable, the argument of keeping it conceptually simpler is compelling—and that probably explains why the variable fonts I looked at did not vary the width of the space with the weight.

Good thought about thin space, etc. I'll check over those.

**Comment by psb1558** [comment]
Surveyed all the spaces, and fixed where necessary. I think we can call this done.
