### ISSUE TITLE
1.067 Two‐ and Three‐em dashes

### ISSUE THREAD

**Issue by marrus-sh** [psb1558/Junicode-font#209]
`U+2E3A` and `U+2E3B` don’t expand or condense to maintain the width of two and three emdashes (respectively) in the Expanded and Condensed widths. These characters are used when typesetting documents according to the Chicago Manual of Style (#2), and while I don’t think it’s a strict requirement that the lengths line up, they do for the Regular.

**Comment by psb1558** [comment]
Thanks, kibigo!!

This is fixed, and will be in 1.068 when I post that (sometime today).
