### ISSUE TITLE
Git tags needed

### ISSUE THREAD

**Issue by alerque** [psb1558/Junicode-font#210]
I just adopted the Arch Linux packaging for this because I realized the version there is ... let me count ... 64 versions behind. That would clearly be a result of the last **tagged* version being 1.003 a couple years back. Arch will be happy to track current releases but a better signal of when actual releases are made (and an easy way to reference specific ones) is needed in the form of tags. They don't have to be marked as GitHub releases (although that brings extra goodies like notifying people that are watching the project) but just a simple tag will do. Please add tags any time the font version number is bumped with the intention of that being a released version. Backporting tags would be an extra bonus useful for diffing font proof sheets using `git bisect` etc, but that is more of a developer thing. For packaging just picking up where you are would be helpful:

```console
$ git tag v1.067 e6effc4
$ git push --tags
```

**Comment by psb1558** [comment]
A couple of questions:

1. What is the hex number?
2. I refrained from releases as long as I didn't think Junicode 2 was ready for the use that would come with being packaged in Linux distros, etc. Should we wait a little while, at least until I change the name back to "Junicode"?

**Comment by alerque** [comment]
The hex number e6effc4 is the commit that you mentioned setting the version to v0.067.

If the font name is different and you don't *want* to invite the usage yet then carry on, don't tag anything yet. Tagging would definitely trigger distros to update and folks to have to deal with the differences downstream.

(font versioning only having 2 segments to work with does make it kind of hard to understand what is meant by them semantically).

**Comment by psb1558** [comment]
> (font versioning only having 2 segments to work with does make it kind of hard to understand what is meant by them semantically).

I know. I would love to be able to include some kind of "beta" indicator, but there seems to be no way to do it. Makes choosing a version number quite a trial.

**Comment by psb1558** [comment]
I think this can be closed now.
