### ISSUE TITLE
fi ligatures and pcap

### ISSUE THREAD

**Issue by RGB-es** [psb1558/Junicode-font#214]
As you can see from the screenshot, fi ligatures are not converted when using pcap feature. Everything works as intended with smcp. 

![junicode2-pcap-fi](https://github.com/psb1558/Junicode-font/assets/7756783/5d60a211-5831-4e9a-8b71-14a008d1d7b2)

**Comment by psb1558** [comment]
Thanks very much! This is a big one, but fortunately was very easy to fix.

**Comment by RGB-es** [comment]
It's now fixed on 2.000beta1. Infinite thanks for this amazing project!
