### ISSUE TITLE
Can't load greek glyphs with Junicode v. 2.000beta1 and XeLaTeX

### ISSUE THREAD

**Issue by Doc73** [psb1558/Junicode-font#215]
Maybe i'm doing something wrong, but greek glyphs aren't working with XeLaTeX. I think there are conflicts with the version installed by CTAN.

As you can see from this example, only bold italics works:

```tex
% !TeX TS-program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT
% !TeX root = Root.tex

\documentclass[11pt,b5paper,article]{memoir}
\usepackage{fontspec,unicode-math}
\setmainfont[]{Junicode}
\newfontfamily\greekfont[Script=Greek,Ligatures=TeX]{Junicode}
\usepackage[babelshorthands=true]{polyglossia}
\setmainlanguage[]{english}
\setotherlanguage[variant=ancient]{greek}

\begin{document}
Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν
ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν
ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον. καίτοι
ἀληθές γε ὡς ἔπος εἰπεῖν οὐδὲν εἰρήκασιν. 

\textit{Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν
ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν
ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον. καίτοι
ἀληθές γε ὡς ἔπος εἰπεῖν οὐδὲν εἰρήκασιν.}

\textbf{\textit{Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν
ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν
ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον. καίτοι
ἀληθές γε ὡς ἔπος εἰπεῖν οὐδὲν εἰρήκασιν.}}

\begin{greek}
Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν
ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν
ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον. καίτοι
ἀληθές γε ὡς ἔπος εἰπεῖν οὐδὲν εἰρήκασιν. 

\textit{Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν
ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν
ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον. καίτοι
ἀληθές γε ὡς ἔπος εἰπεῖν οὐδὲν εἰρήκασιν.}

\textbf{\textit{Ὅτι μὲν ὑμεῖς, ὦ ἄνδρες Ἀθηναῖοι, πεπόνθατε ὑπὸ τῶν
ἐμῶν κατηγόρων, οὐκ οἶδα· ἐγὼ δ' οὖν καὶ αὐτὸς ὑπ' αὐτῶν
ὀλίγου ἐμαυτοῦ ἐπελαθόμην, οὕτω πιθανῶς ἔλεγον. καίτοι
ἀληθές γε ὡς ἔπος εἰπεῖν οὐδὲν εἰρήκασιν.}}
\end{greek}
\end{document}
```

Many thansk in advance,
Domenico

**Comment by psb1558** [comment]
It works for me, though I've got a vanilla TeXLive 2023 installation that includes the older version of Junicode.
<img width="226" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/250fca7d-8dc6-4493-b07b-78aaee25f326">
But I suppose that in your installation fontspec is finding the CTAN Junicode before the newer one. In that case, you can point `\setmainfont` towards the physical font files. There's an example (commented out, and referring to the variable version, which won't work with XeTeX, but still ...) in the [style file for the Junicode Manual](https://github.com/psb1558/Junicode-font/blob/master/docs/JunicodeManual.sty).

**Comment by Doc73** [comment]
Yes, I forgot to mention that I use a Debian system with vanilla TeXLive 2023.
Yes I know that system but maybe I should have rebooted the system but for now I can't do that since I'm working. I'll try restarting and let you know.

**Comment by psb1558** [comment]
I doubt that restarting will do any good. Eventually I trust that Junicode 2 will be in CTAN, but for now I would suggest just referencing the physical font files in `\setmainfont` instead of the family name.

**Comment by Doc73** [comment]
Yes, I can confirm that it doesn't work either by restarting the system or by regenerating the cache.
I managed to get it to work by pointing the direct path to the fonts folder this way:
```
\setmainfont{Junicode}[
  Path = /home/domenico/.local/share/fonts/j/ ,
  UprightFont = {*-Regular},
  ItalicFont = {*-Italic},
  BoldFont = {*-Semibold},
  BoldItalicFont = {*-BoldItalic},
  Numbers={Lowercase,Proportional},
  StylisticSet=10,
  ]%
```

I can wait for the font to officially enter CTAN.
Many thanks,
Domenico

**Comment by Doc73** [comment]
Another possible solution.
Create `~/.config/fontconfig/conf.d/78-Reject.conf` with following text:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
<selectfont>
    <rejectfont>
        <glob>/usr/local/texlive/2023/texmf-dist/fonts/truetype/public/junicode*</glob>
    </rejectfont>
</selectfont>
<fontconfig/>
```

**Comment by psb1558** [comment]
Great solution!

**Comment by psb1558** [comment]
I think this is done now.
