### ISSUE TITLE
LibreOffice gets confused with SemiExpanded and Expanded when trying to use Bold Italic

### ISSUE THREAD

**Issue by RGB-es** [psb1558/Junicode-font#216]
I don't use bold italic that much, but testing the recent Beta version of Junicode I noticed a problem with both, SemiExpanded and Expanded versions. 

I'll use Expanded as example, but it's the same with both versions. 

If I select for a text Junicode Expanded and apply Bold (Ctrl-B), it works, but if I try to make it also italic (Ctrl-I), a fake slanted version is used instead. From the font list I see Junicode Expanded Bold as an independent font (which is odd), but when I apply it LibreOffice shows the Bold Italic version. If I then apply Ctrl-I to that, nothing changes. 

Tested with LibreOffice 7.4.3.

**Comment by RGB-es** [comment]
It works badly on Linux too, but with Junicode each main variant is presented as a separated font, so it can be worked around.

**Comment by psb1558** [comment]
I'll check over the style linking stuff, make sure I've got that right.

**Comment by psb1558** [comment]
I've posted a version (2.000beta2) with shorter style names. Try it out and see if it helps this problem.

Some of the file names have changed, so you need to uninstall the old version before installing the new; otherwise you'll have old files hanging around making your life difficult.

**Comment by kenmcd** [comment]
@RGB-es 
What operating system? And what version?

> recent Beta version

Stuff like "recent" and "latest" mean nothing.
And are often not correct.
Which exact version of the fonts did you test?
Statics or the variable? Or both?
Did you install the variable and the statics at the same time?

> Tested with LibreOffice 7.4.3.

Current "Still" version is: v7.4.7.2
Current "Fresh" version is: v7.5.5.2

**Comment by kenmcd** [comment]
> I've posted a version (2.000beta2) with shorter style names. Try it out and see if it helps this problem.

Where is the link?
I do not see it in the Tags or the Releases.

I was just about to post about this issue.
I can see what is wrong in v2.000beta1.(2023-07-31).tag.
Which is causing the issues above.
But since you have a new beta I should re-check that instead.

**Comment by kenmcd** [comment]
OK. Same issue in v2.000beta2.(2023-08-01).tag
The NameID 1 & 2 are messed-up in both the expanded groups.

Font: Junicode SemiExpanded Bold Italic
File: Junicode-SmExpBoldItalic.ttf
Current 
Name ID 1: `Junicode SmExp Bold`
Should be 
Name ID 1: `Junicode SmExp`
Current 
Name ID 2: `Italic`
Should be
Name ID 2: `Bold Italic`

Font: Junicode Expanded Bold Italic
File: Junicode-ExpBoldItalic.ttf
Current 
Name ID 1: `Junicode Exp Bold`
Should be 
Name ID 1: `Junicode Exp`
Current 
Name ID 2: `Italic`
Should be
Name ID 2: `Bold Italic`

Name ID 1 being wrong puts these fonts in their own style groups - so the style-linking does not work properly (the Bold and Italic buttons give odd results).

**Comment by psb1558** [comment]
Hm. This is how fontmake does it--it's probably gotten confused by my abbreviated style name elements. I'll have to review all the name entries and script corrections when they're wrong.

Thanks for catching this.

**Comment by kenmcd** [comment]
These are affected by some settings in Glyphs - isn't that the source?

**Comment by psb1558** [comment]
But Glyphs isn't generating the fonts--fontmake is. So fontmake is constructing the nametable. Glyphs lets you spell out how you want nametable entries. I can experiment with that and see if fontmake reads those parameters (it may not--it's far from perfect).

Yes—I'll try that first.

**Comment by psb1558** [comment]
Okay, the issue with the Bold Italic faces turned out to be simple: it was just a matter of checking the correct boxes in the instance panels of the Glyphs font info dialog. No fiddling with the name table needed.

Turns out that I was not in compliance with the [Glyphs recommendation on style linking](https://glyphsapp.com/learn/naming) (which I *thought* I had read carefully, but I guess I can be careless sometimes).

Quick preliminary tests: (with static TTF fonts):
InDesign: works well.
Pages: works well.
LuaLaTeX: works well.
LibreOffice: ignores the width axis, but that's what it was doing before.

I'll make a test web page tomorrow--and I suppose I'll have to break out the old Windows box and buy a month or so worth of MS Word.

**Comment by kenmcd** [comment]
> LibreOffice (Mac version): ignores the width axis, but that's what it was doing before.

I will take a look at that tomorrow. Curious as to exactly what it is doing. I now have a VM of macOS 13 Ventura with LibreOffice and Word installed.

Will also test LO and Word on Windows 10.

Assume you will make an updated beta for the testing.

**Comment by psb1558** [comment]
Version 2.000beta3 is in the repository now.

**Comment by RGB-es** [comment]
Beta3 fixed the problem! Closing this.

About the with axis, maybe it's related to this LibreOffice bug? It was reported on Linux and for the variable font, but as far as I understand it, it's a general problem:

[Bug 152396](https://bugs.documentfoundation.org/show_bug.cgi?id=152396) - Font width (expanded, condensed, etc.) is not supported
