### ISSUE TITLE
U+EBBD e᷍a (MUFI) is reversed

### ISSUE THREAD

**Issue by speters33w** [psb1558/Junicode-font#217]
U+EBBD e᷍a (MUFI) is reversed and reads a᷍e

https://mufi.info/q.php?p=mufi/chars/unichar/60349

**Comment by psb1558** [comment]
I'm not seeing this. What version are you using?

**Comment by kenmcd** [comment]
v2.000beta3.(2023-08-02) - 
Checked both VF and static Regular

![uniEBBD](https://github.com/psb1558/Junicode-font/assets/844920/b83faad8-e4fd-41dd-8623-900c7c395e0a)

**Comment by speters33w** [comment]
According to MUFI it's supposed to be e᷍a, not a᷍e. It shows it in the link I gave you.

I'm not really sure why they have that as an individual glyph, since it's just as easy to use `e U+1DCD a` instead of a codepoint, I wouldn't be surprised if the depreciate the glyph.

**Comment by speters33w** [comment]
Using 2.003.

**Comment by psb1558** [comment]
Okay, I've got it. It was a stupid mistake, and it's fixed now.

**Comment by speters33w** [comment]
LOL! 
The fact that it has been like this for, apparently a while, and no-one has complained yet makes me think this glyph (and possibly U+EBBE) might not really be used by anyone...

But then there's a lot of one-off glyphs in MUFI used for one manuscript fragment from somewhere, it's MUFI's purpose in life.

It's just that these two dipthongs - they aren't really ligatures - are easily constructed using existing codepoints.

**Comment by psb1558** [comment]
And it is far better to use the existing codepoints (e, U+1DCD, a), because then users can find the sequence by searching for "ea." Plus, the *e* and the *a* will be kerned with surrounding characters (for technical reasons, PUA characters can't be kerned at all), so the text will look better the fewer PUA characters you manage to use.

**Comment by psb1558** [comment]
Fixed in 2.000.beta4.

**Comment by kenmcd** [comment]
All looks good in both VF Roman and VF Italic v2.000beta4.

**Comment by psb1558** [comment]
That kind of thing can happen (I don't know exactly how) when the glyph is made of components. I decomposed this one to make sure it would remain stable.

**Comment by kenmcd** [comment]
> That kind of thing can happen (I don't know exactly how) when the glyph is made of components.

Element order?
