### ISSUE TITLE
Underdot for Greek letters

### ISSUE THREAD

**Issue by Doc73** [psb1558/Junicode-font#223]
Dear Professor,
underdot is very important in Greek philology, particularly in papyrology: it indicates difficult-to-read letters in the manuscripts.

I tested the position of the underdot and found some issues.
Here is a sample:
```tex
% !TeX TS-program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT
% !TeX root = junicode-underdot.tex

\documentclass[14pt,b5paper,article]{memoir}
\usepackage{fontspec,unicode-math}
\setmainfont[]{Junicode}
%\newfontfamily\greekfont[Script=Greek,Ligatures=TeX]{Junicode}
\usepackage[babelshorthands=true]{polyglossia}
\setmainlanguage[]{italian}
\setotherlanguage[variant=ancient]{greek}

\begin{document}
\section{good}
\d{α} \d{Α}

\d{Β}

\d{ε} \d{Ε}

\d{Ζ}

\d{η} \d{Η}

\d{θ} 

\d{Ι}

\d{Κ}

\d{Μ}

\d{Ν}

\d{ο} \d{Ο}

\d{Ρ}

\d{Τ}

\d{χ} \d{Χ}

\d{ω} \d{Ω}

\section{not good}
\d{β} 

\d{γ} \d{Γ}

\d{δ} \d{Δ}

\d{ζ}

\d{Θ}

\d{ι} 

\d{κ} 

\d{λ} \d{Λ}

\d{μ} 

\d{ν}

\d{ξ} \d{Ξ}

\d{π} \d{Π}

\d{ρ} 

\d{σ} \d{Σ}

\d{ς}

\d{τ}

\d{υ} \d{Υ}

\d{φ} \d{Φ}

\d{ψ} \d{Ψ}

\d{ᾳ} \d{ῃ} \d{ῳ}
\end{document}
```

I attach the corresponding pdf:

[junicode-underdot.pdf](https://github.com/psb1558/Junicode-font/files/12292790/junicode-underdot.pdf)

Thank you very much for all your efforts to improve this excellent, very excellent font.
Domenico

**Comment by psb1558** [comment]
This is done and will be in the next version I post:
<img width="200" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/4bb3bf70-d051-4ea0-9f66-1589fa49710a">

**Comment by Doc73** [comment]
I'm sorry, but there are still some issues.

![Schermata del 2023-08-12 23-10-35](https://github.com/psb1558/Junicode-font/assets/1306260/8873bcc8-fb38-4930-aa2c-971133516ee0)

The latest three glyphs has both yota subscript and undedot.

In general, please consider whether it's appropriate to lower the position of the dot relative to the letters a bit.

Thanks!

**Comment by psb1558** [comment]
I meant to add a bottom anchor to all lower- and uppercase Greek letters. The problem with nu was a typing error; the psi was an oversight.

I have added a bottom anchor to the ypogegrammenicomb. It didn't occur to me that you wanted this because you did not mention it. I welcome requests, and it gives me more than a little pleasure to supply features that users find genuinely useful; but it helps a lot when they make their requests explicit.

The dot below can be lowered a little, but I'm afraid not by much.

**Comment by Doc73** [comment]
A thousand thanks!
The iota subscriptum problem was mentioned in the first post, but actually not clearly. 😄

**Comment by psb1558** [comment]
Crikey! I never scrolled down to p. 2 of the PDF. Spanking retracted.

**Comment by Doc73** [comment]
Thank you very much!
With Version 2.000beta8 all is fine. This issue can be closed. I don't know if I can do it or you prefer to do it yourself.
