### ISSUE TITLE
v2.000beta7 - SmBold vs. Smbold in nameID 1

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#224]
v2.000beta7 - SmBold vs. Smbold in nameID 1

The SemiBold fonts in Normal width, SemiExpanded width, and Expanded width have different names which puts them in different style groups. 
Which is not going to work right in LibreOffice or Word.

`SmBold` in the "regulars" vs. `Smbold` in the Italics.

**Comment by psb1558** [comment]
Oops! Will fix now.

**Comment by psb1558** [comment]
I won't upload this unless you need to see the corrected version. I will only report that, disappointingly, LibreOffice for Mac has not stopped ignoring the width axis.

**Comment by kenmcd** [comment]
I fixed them to test.

> LibreOffice for Mac has not stopped ignoring the width axis.

I assume you are talking about the variable - even on Windows I have had mixed results with variable fonts. When they first started supporting variable I tested a few, and set it aside as not 100% working.

I did get the statics installed on macOS Ventura, and LibreOffice does not show the font styles on the toolbar. I even tried to customize the toolbar to add it - and it is simply not there. The only thing available is "Font Name." 
Weird.
If you edit the paragraph styles you can get to the Family and the Typeface.
Sum Ting Wong.

**Comment by psb1558** [comment]
No, I was talking about the static fonts. If you select, say, "SmExp Bold," you just get Bold in the regular width. I did a little testing with the variable font, and the result was much the same.

I'm told that font selection in LibreOffice for Windows and Linux is much better.

**Comment by psb1558** [comment]
This is done now (though the other issues mentioned here are not necessarily fixed yet).
