### ISSUE TITLE
Missing greek glyphs U+1FC1 and U+037A

### ISSUE THREAD

**Issue by Doc73** [psb1558/Junicode-font#226]
Thanks to the new `Unicodefonttable` LaTeX package, I compared Junicode with CMU Serif and found that the abovementioned glyphs are missing.

For your convenience, I attach the pdf produced by this package. The missing glyphs are marked in red.
Evaluate what to do with it. I'm only interested in those two glyphs.

[Root.pdf](https://github.com/psb1558/Junicode-font/files/12329867/Root.pdf)

**Comment by psb1558** [comment]
They don't strike me as particularly useful, but I don't mind adding them.

**Comment by psb1558** [comment]
This is done now (though the new font is not in the repository yet).
