### ISSUE TITLE
Italic ꜜ in /ꜜꞯ/ do not as /ꜜɴ/.

### ISSUE THREAD

**Issue by kanmurimori** [psb1558/Junicode-font#230]
![屏幕截图 2023-08-18 221101](https://github.com/psb1558/Junicode-font/assets/20810895/9ab379fa-c045-4c0c-8c67-2a6976f435f6)

**Comment by psb1558** [comment]
I take it your modifier down arrow is U+A71C. The problem is that that character is not in the font, so that the browser substitutes the character from a font that has it. I'll add that and  U+A71B.

**Comment by psb1558** [comment]
I've created a new [release](https://github.com/psb1558/Junicode-font/releases), 2.001. The new characters are in it.
