### ISSUE TITLE
Wrong glyph for small ligature FJ (U+EEC9)

### ISSUE THREAD

**Issue by richirisu** [psb1558/Junicode-font#237]
I'd like to point out that the current version (2.003) has a wrong glyph for the MUFI addition of LATIN SMALL LIGATURE FJ at codepoint U+EEC9. The ligature "fr" is displayed instead of the correct "fj".

Fortunately, the glyph for the small ligature FR (U+EECA) is correct.

**Comment by psb1558** [comment]
Thanks. The fix will be in 2.004, which I will post in a few days.

**Comment by psb1558** [comment]
This is fixed.
