### ISSUE TITLE
ss01 implementation is not consistent across all weights

### ISSUE THREAD

**Issue by tarrinw** [psb1558/Junicode-font#241]
The use of ss01 seems to have been reversed (hooray!) in Junicode 2 so that when selected, Old English forms are used for þ and ð - but this is not consistent in all weights.

In implementing the new font in woff2 format on onp.ku.dk I have noticed that the standard woff2 files have the Junicode 2 encoding, as do the Light forms (woff2 files generated myself in FontForge), but Bold and Semibold have the old Junicode 1 values  (again generated myself in FontForge) - headings therefore have a different form for these characters from the main text.

I can get around this by css, but presumably the intention is to use stylistic sets consistently across all weights.

**Comment by tarrinw** [comment]
Looking further into it, this could be a problem with CSS somehow

**Comment by psb1558** [comment]
I'm not sure it's possible to have a different ss01 in different weights, since they are all generated from the same file. Can you share your CSS?

**Comment by tarrinw** [comment]
This seems to be a problem with Chrome (also Safari) rather than with the font. If anyone has a solution I'd be grateful!

**Comment by psb1558** [comment]
I might be able to help if you could either share your CSS or link to the page you're using to test.

**Comment by tarrinw** [comment]
I have tested this on another device and cannot replicate the issue. I think Chrome and Safari (but not Firefox) on my usual laptop are substituting an earlier locally installed version of Junicode 1 in certain parts of the HTML page. They shouldn't do that and the fonts are named differently here anyway, but this is my best explanation of the issue.

I'm therefore closing this issue.

```
/*** Junicode2 (Sept 2023) ***/
@font-face { font-family: Junicode2; src: url(/onp/lib/fonts/Junicode2.004-Light.woff2); font-display: swap; }
@font-face { font-family: Junicode2; src: url(/onp/lib/fonts/Junicode2.004-LightItalic.woff2); font-style: italic; font-display: swap; }
@font-face { font-family: Junicode2; src: url(/onp/lib/fonts/Junicode2.004-Smbold.woff2); font-weight: bold; font-display: swap; }
@font-face { font-family: Junicode2; src: url(/onp/lib/fonts/Junicode2.004-SmboldItalic.woff2); font-weight: bold; font-style: italic; font-display: swap; }
* {
  font-family: "Junicode2", serif !important;
  /* junicode Old Norse thorn and eth (ss01 flipped in Junicode2), ligatures, etc. */
  font-feature-settings: "ss10", "ss15", "kern";
  line-height: 1.25; /*for use with Junicode*/
}
```

Firefox/Gecko (works)
<img width="714" alt="Screenshot 2023-09-28 at 09 26 22" src="https://github.com/psb1558/Junicode-font/assets/34124788/404a6f7f-093f-4ca0-bfbc-c9fc07085307">

Chrome/Blink and Safari/WebKit (inconsistent - see heading and drop-down, but it is unclear why the stylistic set is chosen).
<img width="789" alt="Screenshot 2023-09-28 at 09 25 12" src="https://github.com/psb1558/Junicode-font/assets/34124788/1ec529c3-b569-4c63-8d9d-c50fb1c05f00">

**Comment by psb1558** [comment]
To me it looks as if the language for the heading and the dropdown menu is defaulting to English. Can you explicitly change the language to Danish for those elements?

**Comment by psb1558** [comment]
This could happen if the default language for your laptop is English, but Danish for the other machines you've tested on.

You generally don't need ss01: just set the language correctly, and you'll get the correct shapes of thorn and eth.
