### ISSUE TITLE
tall e (cv10=5) doesn’t work in Irish with ss02 (LibreOffice, Firefox, LaTeX)

### ISSUE THREAD

**Issue by silmeth** [psb1558/Junicode-font#245]
The letter variant for Irish tall e (`cv10=5`) doesn’t work when Insular stylistic set `ss02` is on. This makes it difficult (impossible?) to achieve the right kerning of sequences like *eḋ*. I tried turning `ss02` for *e* character to make it tall (2. in the screenshot), setting the character variants by hand (cv08=2 for Insular d, cv10=5 for tall e) but that doesn’t work with ⟨ḋ⟩ u+1e0b (3.), it works with grapheme joiner (u+034f) but the placement of the dot is wrong (4.).
![meḋraċ ~ meadhrach](https://github.com/psb1558/Junicode-font/assets/5329644/fb5da66c-7c09-4543-abb6-79ab2580fe21)

You showed before this kerning in [a comment on a previous issue](https://github.com/psb1558/Junicode-font/issues/180#issuecomment-1587119965):
![](https://user-images.githubusercontent.com/16215767/245118611-1d53f4a7-b496-4747-97c5-c7cfbf14ac46.png)

Is it possible to get that with the current version?

**Comment by silmeth** [comment]
And the same using XeLaTeX.

Source code:
<details>
  <summary><code>test.tex</code></summary>

  ```latex
  \documentclass[10pt, a5paper]{article}
  \usepackage[top=0.5in,right=0.5in,left=0.5in,bottom=0.7in]{geometry}
  \usepackage{fontspec}

  \usepackage[english,irish]{babel}

  \setmainfont{Junicode}[
      ItalicFont={*-Italic},
      Language=Irish,
   ]

  \begin{document}

  \begin{enumerate}
      \item  { \Huge \addfontfeature{StylisticSet=2} \addfontfeature{CharacterVariant=10:5} meḋraċ } (Junicode:ss02\&cv10=5)
      \item  { \Huge \addfontfeature{StylisticSet=2} m{\addfontfeature{CharacterVariant=10:5}e}ḋraċ } (Junicode:ss02; Junicode:cv10=5 on e)
      \item  { \Huge \addfontfeature{CharacterVariant=8:1} \addfontfeature{CharacterVariant=10:4} meḋraċ } (Junicode:cv08=2\&cv10=5)
      \item  { \Huge \addfontfeature{CharacterVariant=8:1} \addfontfeature{CharacterVariant=10:4} med͏̇raċ } (Junicode:cv08=2\&cv10=5 + d + grapheme joiner + dot above)
  \end{enumerate}

  \end{document}
  ```
</details>

the result:
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/994253f0-0fd1-4200-8589-0fc468d3a644)

**Comment by silmeth** [comment]
Found a work-around for LibreOffice – applying `ss02` only to a part of the word via `Junicode:ss02[2:]&cv10=5`.
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/8ee4f745-c83e-48b3-9fda-acd1acaedd47)

Not sure how do that elsewhere (but I guess there is a way?).

**Comment by psb1558** [comment]
Yeah, something is wrong. This is going to take some thought.

Stay tuned.

**Comment by psb1558** [comment]
> Found a work-around for LibreOffice 

I'm working on something easier to use.

**Comment by psb1558** [comment]
In the next version, this will work:

- Make sure the language is set to Irish
- Turn on ss02
- Turn on cv10=4, preferably for the whole word containing `eḋ`, but at least for the whole sequence `eḋ`.

In LuaLaTeX or XeLaTeX, this source
```
\documentclass[10pt, a5paper]{article}
\usepackage[top=0.5in,right=0.5in,left=0.5in,bottom=0.7in]{geometry}
\usepackage{fontspec}

\usepackage[english,irish]{babel}

\setmainfont{Junicode}[
    ItalicFont={*-Italic},
    Language=Irish,
 ]

\begin{document}

\noindent This works:\\
{ \Huge \addfontfeature{StylisticSet=2}m{\addfontfeature{CharacterVariant=10:4}eḋ}raċ }\\[1ex]
note also:\\
{ \Huge \addfontfeature{StylisticSet=2}m{\addfontfeature{CharacterVariant=10:4}ed}raċ }\\
{ \Huge \addfontfeature{StylisticSet=2}m{\addfontfeature{CharacterVariant=10:4}e\char"034F\char"0301d}raċ }\\
{ \Huge \addfontfeature{StylisticSet=2}m{\addfontfeature{CharacterVariant=10:4}e\char"034F\char"0301ḋ}raċ }

\begin{enumerate}
    \item  { \Huge \addfontfeature{StylisticSet=2} \addfontfeature{CharacterVariant=10:4} meḋraċ } (Junicode:ss02\&cv10=5---this is best)
    \item  { \Huge \addfontfeature{StylisticSet=2} m{\addfontfeature{CharacterVariant=10:4}e}ḋraċ } (Junicode:ss02; Junicode:cv10=5 on e---fails because of formatting boundary between e and ḋ)
    \item  { \Huge \addfontfeature{CharacterVariant=8:1} \addfontfeature{CharacterVariant=10:4} meḋraċ } (Junicode:cv08=2\&cv10=5---okay but cv08=2 is superfluous if ss02 is on)
    \item  { \Huge \addfontfeature{CharacterVariant=8:1} \addfontfeature{CharacterVariant=10:4} med͏̇raċ } (Junicode:cv08=2\&cv10=5 + d + grapheme joiner + dot above---fails because of CGJ:
    d + dot should be allowed to resolve to U+1E0B)
\end{enumerate}

\end{document}
```
will produce this PDF:
[e-test.pdf](https://github.com/psb1558/Junicode-font/files/12908526/e-test.pdf)

It may be a week or so before the next release.

**Comment by silmeth** [comment]
Closing – as seems to be done and working as expected in 2.200.
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/758d405a-c717-4062-be85-82cfb3113dc9)
