### ISSUE TITLE
Enabling hlig feature causes display problems in Libreoffice

### ISSUE THREAD

**Issue by Doc73** [psb1558/Junicode-font#246]
It's a small but annoying bug.

Below is a video demonstrating the problem:

[Video del 2023-10-15 18-35-42.webm](https://github.com/psb1558/Junicode-font/assets/1306260/c5a50823-6732-4e69-bbaf-9c116f040a66)

Thanks in advance.

**Comment by psb1558** [comment]
I'm not sure what you mean. You're enabling hlig, not dlig, and (apparently) typing one character, which would not ligature anyway. What are dnom and frac (normally not used together) all about? What are you expecting to see (and what is the difference from what you're actually seeing)?

**Comment by Doc73** [comment]
Yes! My was a typo. Here some screenshots
![Schermata del 2023-10-15 19-28-20](https://github.com/psb1558/Junicode-font/assets/1306260/422fa258-0a9c-41b2-887c-ac2c6cd76294)
![Schermata del 2023-10-15 19-28-35](https://github.com/psb1558/Junicode-font/assets/1306260/17d050f1-9ea9-4a5d-9f64-94867341d253)
Please, take a look at how the font name is displayed

**Comment by psb1558** [comment]
Oh! Yes, that looks very strange! But it's just LibreOffice applying selected OpenType features to the display of the font name and the style names, which double (oddly) as previews. Not a bug in either Junicode or LibreOffice, but just the way LibreOffice has chosen to do things. Here's my copy doing the same thing:
<img width="327" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/34549bfb-9b61-4cf3-94fc-c3101c6b0782">
It's even weirder if I turn on Latin-to-Gothic transliteration:
<img width="325" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/58e7bfd6-3a1f-4854-bde9-ff26b54f9258">
I can't see a way to turn off this feature in the LibreOffice preferences (admittedly I just skimmed them). Perhaps you could lobby the LibreOffice team for a way to turn it off.

**Comment by Doc73** [comment]
It's true: I hadn't thought of that!
You can close this report!
Many thanks!

**Comment by psb1558** [comment]
Glad to help.

**Comment by khaledhosny** [comment]
> I can't see a way to turn off this feature in the LibreOffice preferences.

Not in preferences, but in 
<img width="319" alt="Screenshot 2023-10-16 at 12 46 59 AM" src="https://github.com/psb1558/Junicode-font/assets/93914/a7663ecb-6d22-410a-b130-c1edd676696e">

**Comment by psb1558** [comment]
Cool! How did I overlook that all this time?
