### ISSUE TITLE
Manual p. 51l. 1 from the top: incorrect display

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#250]
Although the code contains correctly  F000F, I see FoooF. It's only me? I use evince on stable Debian.
![FoooF](https://github.com/psb1558/Junicode-font/assets/8024702/c1d835b2-8672-41fd-9762-b38bd2a40b10)

**Comment by psb1558** [comment]
That's an oversight. Junicode now defaults to old-style numbers. I thought I had changed all the hex numbers in this table to use lining figures, but I missed a few special cases (17, to be exact). I have corrected these now.

**Comment by psb1558** [comment]
Now fixed in the manual for version 2.203.
