### ISSUE TITLE
Applying Irish + ss02 uses long s instead of insular in ‘st’

### ISSUE THREAD

**Issue by silmeth** [psb1558/Junicode-font#251]
Noticed this [on Wikisource](https://en.wikisource.org/wiki/Template:Insular) since Wikimedia updated Junicode to 2.100 in their language selector, checked this in 2.200 too.

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/b0ab8eed-0b3e-41b9-a3b8-48e326742676)

I’d expect the insular glyph here, not long s. It’s also inconsistent with ‘ṡt’ which is rendered using the insular shape (although that’s not a combination that would appear naturally in Irish).

**Comment by psb1558** [comment]
Yes. That's been a feature for a long time, since _st_ is generally rendered as _ſꞇ_ in Old English manuscripts. If the same is not true for Irish I can make it an English-only rule.

**Comment by silmeth** [comment]
I’m not sure about the manuscript usage – but I haven’t seen long s in Irish print.

**Comment by psb1558** [comment]
Well, I'll make the change. One could always work around it to get the long s. New release probably this weekend.

**Comment by psb1558** [comment]
This is done.
