### ISSUE TITLE
Characters "ə" and "ɜ" not scaling when using ENLA property

### ISSUE THREAD

**Issue by pietrogregorini** [psb1558/Junicode-font#253]
Hello everybody!
I noticed an issue when using the ENLA property in variable version, where two glyphs "ə" and "ɜ" are not scaling together with the rest of the letters – in Italy we use those glyphs in texts where inclusivity is important.
By the way, the same issue occours with rare ligatures.

<img width="1021" alt="Screenshot 2023-11-14 alle 13 58 02" src="https://github.com/psb1558/Junicode-font/assets/3169323/1f165c1e-4a97-429f-9931-79ef0ac549a0">

It would be nice to correct this issue :)

Thanks!

**Comment by psb1558** [comment]
ENLA is not meant for running text, but is rather about handling _litterae notabiliores_ in medieval texts—single letters at the beginnings of sentences and other textual units. So it only affects letters that are likely to appear in that particular context. Nothing that occurs only in modern text, and no ligatures.

It sounds like you may be looking for a font with an optical size axis. My Elstob font has that, and there are other good free fonts with an optical size axis--Roboto Serif comes to mind.
