### ISSUE TITLE
Dot above placement (d ḋ vs. b ḃ / f ḟ) 

### ISSUE THREAD

**Issue by Moilleadoir** [psb1558/Junicode-font#254]
In the context of Irish text, the positioning is good when using the Insular variants (ss02) but with Roman letters lowercase D & F could do with tweaking.  Ideally D should mirror B and the dot should be visually centred on F.  At the moment it looks like the dot is sliding off the F.

![pic](https://github.com/psb1558/Junicode-font/assets/1229543/92738d59-ad7a-4e9f-8cf3-38ee669d5685)

**Comment by psb1558** [comment]
I have changed the placement of the dot in U+1E0B (ḋ) to match that of U+1E03 (ḃ). I'll note that anyone wanting the higher position of the dot on either of these glyphs can get it with the sequence <base glyph> U+034F U+0307.

These is no agreement among fonts I think of as authoritative on the placement of the dot on U+1E1F (ḟ). For example, here is the glyph in Brill, Liberation Serif, and Gentium Plus:
<img width="118" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/e4ef7174-6336-4eb4-9bd5-501bc203408c">
Brill centers it over the vertical stem, Liberation over the top of the bow, Gentium at a (compromise?) point between. Obviously there is a constituency for each position, but I decided I liked Gentium's approach.

The changes for U+1E0B and U+1E03 will be in the next release (2.204).
