### ISSUE TITLE
Underdotted text feature for Greek

### ISSUE THREAD

**Issue by jakub-simek** [psb1558/Junicode-font#259]
Dear @psb1558 ,

The Open Type feature for underdotted text in the new Junicode is very useful for marking unclear or uncertain readings of characters following a convention in classics and especially papyrology. In papyrology the dots are very common because most of the edited sources are fragmented or damaged in some way. 

When trying this feature out I have noticed that it does not work for Greek characters. May I ask if you could consider adding this feature to Greek characters as well?

**Comment by Doc73** [comment]
https://github.com/psb1558/Junicode-font/issues/223

**Comment by psb1558** [comment]
Actually this is looking to be even easier than I thought. So I'll ask instead: should I include the archaic characters? Any non-alphabetic characters?

**Comment by Doc73** [comment]
@psb1558 Underdots are very useful with all greek glyphs, even with numerals

**Comment by psb1558** [comment]
It's partway there, but seems to be working for some characters and not others. Not, apparently, in Greek Extended. It will take a while to figure out what's going on.
<img width="413" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/0b657993-6362-4d06-a782-1324bc7f2993">

**Comment by jakub-simek** [comment]
> Underdots are very useful with all greek glyphs, even with numerals

I agree with @Doc73 . Thank you very much, @psb1558 , for implementing it, even if it might still take some effort. The feature (together with the archaic characters) will make the font very attractive for papyrologists.

**Comment by psb1558** [comment]
It's all working well now--so very well that I've revised the Latin lookup to work like the new Greek one (for geeks like me, I'm using a Type 2 "Multiple Substitution" lookup to replace any glyph with a "bottom" anchor with that glyph + U+0323 combining dot below--the first time Junicode has used this type of lookup).

I have uploaded a [preview of version 2.204](https://github.com/psb1558/Junicode-font/tree/master/fonts/variable) (variable roman only!) for testing.

Query for @Doc73: what do you mean by "including numerals"? Are you talking about [Greek numerals](https://en.wikipedia.org/wiki/Greek_numerals), or Arabic?

Next step is to implement in the italic face.

**Comment by psb1558** [comment]
Small caps too.
<img width="373" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/10bcb0b6-9fe6-4e97-8144-6f08bd1b5242">

**Comment by Doc73** [comment]
@psb1558 yes, greek numerals

I'm sorry, but we philologists are quite annoying! :smiling_face_with_tear:

**Comment by psb1558** [comment]
@Doc73: I thought they were just letters repurposed. I don't have anything from the "Ancient Greek Numbers" Unicode block.

**Comment by psb1558** [comment]
Trouble is, I have very little idea what Polyglossia is doing here--how it tries to produce its shapes. But it does happen sometimes that an environment switches off or mangles OpenType features activated before it begins. Without knowing more of what's going on in `\greeknumeral` (the polyglossia documentation is vague), it's hard to say more. But have you tried `\greeknumeral{\d{}}`?

In any case, Junicode is behaving in accordance with the specification when ss07 is applied:
<img width="72" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/77e60544-2a8d-4c7a-95da-f1de581ef34b">
If my suggestion above doesn't work, perhaps you should take the issue to some forum where polyglossia is covered. If you do, you might frame the issue as an OpenType stylistic set being ignored for all but the last character in the `\greeknumeral` environment, and mark positioning being disabled for that one character.

**Comment by psb1558** [comment]
The revised feature is in version 2.204, released today.

**Comment by jakub-simek** [comment]
Thank your very much for implementing the feature so quickly, @psb1558 ! I have installed the new release 2.204 and tried it in InDesign. However, now the feature does not seem to work for any letters, Greek or Latin. I am accessing it in InDesign through "OpenType > Stylistic Sets > Underdotted" in the "Character" palette. It worked in the previous version 2.203 as expected for Latin letters (and not for the Greek ones) but now in 2.204 the dots don't appear under any glyph. I have tried it with installing both the OTF and TTF versions, but the feature doesn't work for me in any of them. In JunicodeVF neither. Has something changed perhaps in the way how the feature should be accessed? I've tried it in InDesign only so far.

**Comment by psb1558** [comment]
In the "Paragraph Style Options" dialog, go to the "Justification" tab and change "Adobe Paragraph Composer" to "Adobe World Ready Paragraph Composer." The *Junicode Manual* (p. 10) suggests doing this when using the variable font with InDesign, but actually you should *always* do it, whatever font you're using, because there are OpenType features that the standard composer can't handle (and this, of course, is one of them).
<img width="548" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/64e37b7a-6475-4c5a-95a0-8fdfd9431887">

**Comment by jakub-simek** [comment]
Thank you very much for the hint, it works great with the "Adobe World Ready Paragraph Composer".

May I just revisit the suggestion of @Doc73 concerning numerals? I would very much welcome the "underdotted" feature for numerals as well - normal arabic numerals. If editions use the underdots as means of visualizing uncertainty, practically any glyph appearing in historical sources can be concerned (excluding only invisible spaces and combining marks). Even punctuation marks might need the feature because they as well can be marked up as unclear or uncertain.
