### ISSUE TITLE
An idea for ⟨ĥ⟩; ligatures and fine details

### ISSUE THREAD

**Issue by theblursed** [psb1558/Junicode-font#261]
Dear psb1558,

Thank you very much for the correction of the small details I proposed you, which you implemented so fast. You’re very gentle. 🙂

I’m now writing you again, for other esthetic suggestions on fine details.

1. I’m currently writing a text about Esperanto, and I tried to typeset it in Junicode. I noticed that for `ĥ` (which frequently poses a challenge to designers) you put the circumflex in the middle of the blank space on top of the letter:
![Schermata 2023-12-17 alle 12 47 47](https://github.com/psb1558/Junicode-font/assets/134559730/abee125f-87bd-490d-b58e-70395fc4923e)
While common, sincerely speaking I’ve never found this shape attractive. To my eyes, it appears unbalanced in itself and not in harmony with the other circumflexed letters of the language:
![Schermata 2023-12-17 alle 12 54 00](https://github.com/psb1558/Junicode-font/assets/134559730/900d406c-ce4a-45c0-ad54-1dd555d7c3f2)
Beyond the personal tastes, which are inevitably subjective, I think there’s a problem for legibility: the diacritic is so high and far from the main “body” of the letter that it can easily be overlooked, especially in linguistic texts that rely on many symbols, diacritics, abbreviations, etc. and so often are quite “dense”.

![Schermata 2023-12-17 alle 12 49 21](https://github.com/psb1558/Junicode-font/assets/134559730/9ad29c43-8ae9-4bde-a97c-3fc7be42d1ef)

The rarer variant with the circumflex on the side of the ascender in my opinion solves both issues beautifully. See a comparison with Libertinus Serif:
![Schermata 2023-12-17 alle 13 00 41](https://github.com/psb1558/Junicode-font/assets/134559730/a6bf3c0f-0097-493a-97ec-848956c50772)
For Junicode, if you like the idea it may need the circumflex on the _h_ to be a little narrower. A fast mockup:
![mockup](https://github.com/psb1558/Junicode-font/assets/134559730/e8214419-4479-4a4d-b0c1-3ffe3fc57b04)
...But maybe it could work also if it was instead _wider_ (like it is now on top of the letter) and touched the ascender. 🤔
![Schermata 2023-12-17 alle 12 54 00 copia](https://github.com/psb1558/Junicode-font/assets/134559730/38b254b9-d228-404f-8eba-78bf22e13b96)
2. When writing in IPA, for the phonemic stress I follow the rare but more precise convention of writing it not before the syllable (/afˈfa/) but directly on the vowel (/affa̍/) for the many languages in which syllabic division is not phonemic but only phonetic (for example Italian: _menò_ /menɔ̍*/ [meˈnɔ]). For such usage, to avoid a collision or an excessive narrowness, it may be useful to have the top terminal of `f`, `ʃ` and `ʧ` to “retract”, or the space between letters to enlarge, before `i̍`, as it happens for `fí`, `ffí`.
![Schermata 2023-12-17 alle 13 39 51](https://github.com/psb1558/Junicode-font/assets/134559730/bb8c4daa-5e2d-4e63-820c-7cb5f3c91af5)
3. The same thing could be beautiful for `ʃí`, `ʃî`. (I don’t know if and how it could be done for `ʃï`…). 
![Schermata 2023-12-17 alle 15 28 00](https://github.com/psb1558/Junicode-font/assets/134559730/77df5e14-e5c1-4b08-bf01-d73a16f82708)
4. In my very personal opinion, `fí` and `ffí` would look better and be more coherent if the _i_ was actually joined with the _f_(s), as it happens in `fi` and `ffi`: it is strange and not very pleasant that the addiction of an accent breaks the ligature (an _i_ is still an _i_, with or without an accent). The same can be said of other diacritics. See a comparison with other typefaces:
![Schermata 2023-12-17 alle 15 06 42](https://github.com/psb1558/Junicode-font/assets/134559730/ed0f6554-4e66-4d14-bf77-507db1c4b98b)
Befter:
![Befter](https://github.com/psb1558/Junicode-font/assets/134559730/a98656dd-fd3e-49b9-942e-db0916a27111)
Barracas:
![Barracas](https://github.com/psb1558/Junicode-font/assets/134559730/fc2eca2c-1d53-4137-aa22-eaa54f80b8f0)
Marseille:
![Marseille](https://github.com/psb1558/Junicode-font/assets/134559730/0ae704db-375e-474b-8811-9f6c05b5004f)
These are only ideas, personal preferences! And for fine details. I hope I'm not annoying. 🙂
Thank you for you work again.

**Comment by alerque** [comment]
Not everyone is happy with *Libertinus Serif* the way it is now ant I think it will eventually get an alternate.

c.f. https://github.com/alerque/libertinus/issues/329

**Comment by theblursed** [comment]
Hi Alerque. 🙂 I read that discussion some time ago. For what I know of Esperanto, which I’ve been actively interested in for some years now (to give a measure, I’ve got a full shelf in my library only for Esperanto books) I think the matter has been summed adequately by Georgd:

> There's no right or wrong on any of the three forms. They can all be seen throughout the history of Esperanto typesetting, though admittedly the present version is the least common. I'd generally refrain from categorising in right and wrong upon such questions as this is about design which is about aesthetics, a highly subjective matter.

And I wanted to let Psb1558 know that other design choices are possible and (IMHO) both esthetically and legibly preferable.
As for Libertinus, alternates are good, but (in general) I suggest you don’t feel forced to change your (beautiful!) design choices just because of one over-aggressive commentator... 😛

Other fonts with the circumflex on the side of the ascender:

Libre Baskerville:
![Libre Baskerville](https://github.com/psb1558/Junicode-font/assets/134559730/c1be2efb-4438-4c90-8e56-cdfb1f397039)

Caveat:
![Caveat](https://github.com/psb1558/Junicode-font/assets/134559730/c67cc007-d995-40f4-ba5c-3d4910a977a6)

Shadows Into Light:
![Shadows Into Light](https://github.com/psb1558/Junicode-font/assets/134559730/a320faae-6604-49a8-bbed-77ca40269f4a)

Indie Flowers:
![Indie Flowers](https://github.com/psb1558/Junicode-font/assets/134559730/5e51ee1a-de21-48e1-bfaa-c1e52ff495e8)

Domine:
![Domine](https://github.com/psb1558/Junicode-font/assets/134559730/6c9e4f37-a798-4849-a455-4323c5c5fd18)

Frank Ruhl Libre:
![Frank Ruhl Libre](https://github.com/psb1558/Junicode-font/assets/134559730/00c9ad39-cd57-48a2-8e07-09a4fa758cfb)

Righteous:
![Righteous](https://github.com/psb1558/Junicode-font/assets/134559730/87e4d26f-daea-4cd5-b026-c62a8e345641)

Gruppo:
![Gruppo](https://github.com/psb1558/Junicode-font/assets/134559730/926a1139-e3b5-4b01-8fd8-54908a63d334)

Libre Caslon Text:
![Libre Caslon Text](https://github.com/psb1558/Junicode-font/assets/134559730/293b25fa-c83d-4bde-a160-90b73369ec61)

And many others surely can be found.

**Comment by theblursed** [comment]
Some other typefaces with the circumflex on the side, which I found just scrolling through Google Fonts:

BioRhyme, Titan One, Marck Script, Audiowide, Aclonica, Quintessential, Petit Formal Script, Caudex, Besley, Fondamento, Peralta, Ribeye, Charmonman, Glass Antiqua, Rum Raisin, Cantora One, Uncial Antiqua, Spicy Rice, Milonga, Margarine, Risque, New Rocker, Galindo, Plaster, Ribeye Marrow, Special Elite, Mouse Memoirs, Bruno Ace

**Comment by psb1558** [comment]
ĥ: ss20 substitutes low-riding diacritics for some that normally sit high above letters like h and b. I have added the combining circumflex to that feature, so with ss20 you'll get, for the sequence h U+034F U+0302:
<img width="48" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/64603153-bcdf-4a06-b9c2-3cfa35322275">
This will *not* work with the precomposed character U+0125, and you need U+034F to prevent the h+mark sequence being turned into U+0125.

f + lowercase letter + mark: This sequence will trigger substitution of narrow f for standard f. So you'll get:
<img width="129" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/6c818ff2-310b-4575-9674-73748bc15404">
and many more combinations will be affected.

Narrow version of esh U+0283: Good idea. I will do this.

Ligatures of f with i+mark: I am satisfied with the way Junicode is handling these sequences now.

These changes will be in the next release (whenever that comes along).

**Comment by theblursed** [comment]
Thank you very much 🙏🙂

**Comment by alerque** [comment]
> This will _not_ work with the precomposed character U+0125

Why not? This doesn't sound like a valid technical limitation from the font engineering side of things.

**Comment by psb1558** [comment]
Just because I haven't implemented it that way. Right now ss20 manages 18 combining marks. If I get it into the business of also managing composites like U+0125, it will grow to become one of the font's bigger maintenance headaches. This will sound selfish, but I'm fine with asking folks who want something a little unusual to do a little more to get it.

And then, Junicode's GSUB features are already so huge that they are causing overflow errors in Glyphs, so I can no longer test within the font editor--a major pain. I would love to put the brakes on the growth of this font, or even find a way to compress or cut back a little.

**Comment by alerque** [comment]
Okay, that's fair. It just sounded like you thought there was some reason you could not, not some reason you would not. "Won't" is fair, the "can't" just sounded wrong to me.

Still the trouble you describe sounds like a Glyphs problem more than anything else. I'm not a Glyphs user and know more about the backend how fonts are stored and used, but this shouldn't result in more work for a font designer, both the precomposed and combining sequences should be covered by the same feature set across the board. It sounds like something (likely Glyphs not you) has jinxed this and created two paths that need fiddling with even though they eventually merge and could have been changed at a single point.

**Comment by psb1558** [comment]
Since fontmake compiles without complaining about overflow errors in GSUB, I do expect that I'm running into a bug in Glyphs. Last time I tried to report an overflow error (in GPOS) as a  bug, though, I was told it was my fault for putting in too many anchors.

So I'm not going to report this one as a bug.

**Comment by alerque** [comment]
> I was told it was my fault for putting in too many anchors.

How many anchors do you *have*? You aren't putting unique anchors for each possible diacritic are you?

**Comment by psb1558** [comment]
> How many anchors do you have? You aren't putting unique anchors for each possible diacritic are you?

No, but in addition to the usual collection (the things Glyphs adds automatically), U+1DD2 combining -us has its own anchor (since I eccentrically insist that it must be positioned differently from other marks), and U+1DCE combining ogonek above, and some variants of U+035B combining zigzag. And then I have propagation of anchors in composites turned on, and lots of anchors on glyphs that aren't down in the Glyphs database as requiring them. I don't think there are so many as to cause problems, but rather something about my rather complex GPOS is triggering an obscure Glyphs bug.

**Comment by theblursed** [comment]
In the last weeks I’ve bought or had scanned some Esperanto books or magazine articles (all of them about linguistics) for the text I’m preparing. Less than ten in total, yet in at least four of them I found the _h_ with the low circumflex (just by chance: I’m not researching that). I’m posting here the pictures not to ask any change in Junicode (I already tried the new solution and it displays perfectly: thank you very much again, @psb1558 🤗), but to provide useful examples to anybody who may find and read these discussions, whether they are type-designers or Esperantists, about this letter-shape.

Ebbe Vilborg, _Esperantigo de grekaj nomoj_, in _Esperantologio_, July 1961:

![Schermata 2024-01-09 alle 16 01 29](https://github.com/psb1558/Junicode-font/assets/134559730/65e1063a-c05c-4625-80ee-ea81700a16af)

Tadeusz J. Michalski, _Kiel esperantigi polajn geografiaĵojn_, in _Pola Esperantisto_, January-April 1975:

![Schermata 2024-01-09 alle 16 13 09](https://github.com/psb1558/Junicode-font/assets/134559730/49faa212-bd71-48ed-918e-824ac11dfaaa)

![Schermata 2024-01-09 alle 16 12 16](https://github.com/psb1558/Junicode-font/assets/134559730/bfa529b4-0157-4e4c-8727-c829f6a76734)

Josef Kavka, _Esperantigo de la ĉeĥoslovaj loknomoj_, in _Scienca revuo_, vol. 29, 1978

![Schermata 2024-01-09 alle 16 31 12](https://github.com/psb1558/Junicode-font/assets/134559730/787899e3-0f82-4399-8439-5ceebbe8775d)

Bernard Golden, _Principoj por la esperantigo de hispanlingvaj vortoj kaj propraj nomoj_, in _Serta gratulatoria in honorem Juan Régulo_, vol. II, 1987

![chfhf](https://github.com/psb1558/Junicode-font/assets/134559730/1e26a9d6-4401-4b66-b561-256e5d728916)

**Comment by psb1558** [comment]
It's a classic problem in font design that a glyph for one language looks a little different from a glyph for another. One might say, Well, so what? but it means something to readers and writers of the affected languages, and so it has to be dealt with. OpenType has an excellent mechanism for dealing with the issue, namely to swap out one glyph for another when the language is this or that. Junicode does this for English, Irish, Turkish, Romanian, and a number of other languages.

Of course, that only works when there's substantial agreement about usage within a language community, and this is not the case with Esperanto. So you get the manual solution I provided.

With some glylphs, there's a preferred form, but printers compromise when the preferred form is absent from a font. I was wondering what old Zamenhof would prefer. In *Fundamento de Esperanto* (1905), one finds this:
<img width="128" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/b303f622-ee2e-470f-a79d-8575b5cf734e">
But I can't tell where [this copy](https://archive.org/details/FundamentoDeEsperanto/page/n1/mode/2up) was printed—not sure whether Zamenhof had much to do with the printing.  In *Dr. Esperanto's International Language*, trans. R. H. Geohegan and printed in Warsaw 1889, so presumably under Zamenhof's supervision or influence, one finds this (p. 36):
<img width="118" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/6b63bfc8-8b8e-4e5b-8c66-ea5067171738">
But I couldn't find much more, at least in early prints that seem at all authoritative (lots of early copies were printed far from Warsaw).

It's quite possible that Zamenhof didn't care about this at all--after all, he seems to have had nothing to say about it. It would be interesing to get hold of some of his manuscripts, but I haven't managed that.

**Comment by psb1558** [comment]
I think this is as complete as it's going to be (for now anyway), so I will close.

**Comment by inferno986return** [comment]
This is a very thorough issue thread and I have comparatively little to add here:

1. Esperanto-ĥ will always be tricky as it's one of the few ascender-height letters to have a diacritic above it.
2. From starting a thread for the Darwin typeface, I found there is no consensus I can find on the best placement of the circumflex above Latin lowercase "h": https://github.com/topological-modular-forms/Darwin-Typeface/issues/59
3. My solution is to have stylistic alternates for each circumflex placement: ontop of stem (my preferred placement), centred (default for automated circumflex placement), and on top of the shoulder (used in Libertinus Sans)

I don't think Zamenhof himself cared about the placement of lowercase letter "h" as the goal was to have distinctive diacritics which could be typed with the contemporary French typewriters of the time.
