### ISSUE TITLE
Font export fails

### ISSUE THREAD

**Issue by tarrinw** [psb1558/Junicode-font#268]
Export 2.206 from Glyphs 3 (3.1.2) fails with error:

The operation couldn’t be completed. Problem compiling “GPOS” tableSubtable Overflow in lookup: 18 type: MarkToLigatureAttachment

**Comment by psb1558** [comment]
Junicode has been breaking Glyphs export for quite a while, and I haven't tried to fix because I think of the Open Source method (using Open Source tools) as more important for this Open Source font. See "Building Junicode" on the [main repo page](https://github.com/psb1558/Junicode-font).

**Comment by tarrinw** [comment]
Thanks - that works well.
