### ISSUE TITLE
Old Polish b/p quadratum/rotundum as PLK in ss09

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#27]
These characters are often mentioned in the literature on the history of Polish but cannot be quoted because the glyphs are not available.
For more information see pages 8-10 of https://www.researchgate.net/publication/350449200 (now a slightly modified published version temporarily behind a paywall: https://www.researchgate.net/deref/https%3A%2F%2Fwww.ceeol.com%2Fsearch%2Farticle-detail%3Fid%3D1058326) and/or pages 42-43 of https://pressto.amu.edu.pl/index.php/pspsj/article/view/19852.

**Comment by psb1558** [comment]
Interesting. I'd like to be very clear about what differentiates b/p molle from the regular b/p. For the italic I can see the difference in the images from Kucała, but it would also help (especially for figuring out what the roman should look like) to see what regular b/p look like in the manuscript you cite.

**Comment by jsbien** [comment]
Parkosz had no intention to use regular p/b and the manuscript is copy made by two scribes with different handwriting styles. Below please find some examples from the first and second part of the treatise.
![parkosz3eligibilitatem](https://user-images.githubusercontent.com/8024702/86767539-6acba580-c04c-11ea-8aaa-193c5f7f6409.png)
![parkosz13scribamus](https://user-images.githubusercontent.com/8024702/86767541-6b643c00-c04c-11ea-8dda-df650c8c2af6.png)
![parkosz3Topicorum](https://user-images.githubusercontent.com/8024702/86767938-09580680-c04d-11ea-8d43-4cfc57bf7cc6.png)
![parkosz15exempla](https://user-images.githubusercontent.com/8024702/86767939-09f09d00-c04d-11ea-944e-f1c88297e7fc.png)

**Comment by jsbien** [comment]
The thread on MUFI-fonts list (accessible only by subscribers): https://groups.google.com/forum/#!topic/mufi-fonts/fmncUGKG9Kw.

**Comment by jsbien** [comment]
Just an idea for b sharp (my very first drawing in Gimp...). 
![bsharp](https://user-images.githubusercontent.com/8024702/89145295-a759c680-d550-11ea-989a-1a5bf196c22c.png)

**Comment by psb1558** [comment]
Sorry I've been neglecting this. Getting ready for another term on Zoom, and then supplying hints for Elstob.

I'm still having trouble visualizing what these glyphs should look like, but will post some ideas when I get a chance.

I'm a big Gimp fan, btw.

**Comment by jsbien** [comment]
There is no hurry, Parkosz can wait :-)

**Comment by jsbien** [comment]
I've prepared a note about encoding Parkosz's alphabet with a tag character. Please contact me (preferably by mail) if you want to have a look.

**Comment by psb1558** [comment]
The Parkoza tract is fascinating, and it's great to have both the MS facsimile and a modern edition to work with. I've been thinking about what glyphs should be added to handle it. This is kind of rough, but a start:
<img width="444" alt="image" src="https://user-images.githubusercontent.com/16215767/186068883-955f99dc-834f-4c05-b0c5-251d23706bcc.png">
We can discuss the tags once the collection of glyphs is settled.

**Comment by jsbien** [comment]
Very nice! Thanks!
B durum and b molle are easy to distinguish thanks to the loop, but I'm afraid p durum i p molle look too similar for a typical reader.

**Comment by psb1558** [comment]
I'll fiddle with those shapes a bit. They're difficult because they've got shapes that are hard to fit into a standard roman design scheme.

The p molle looks to me like an ordinary late-gothic p. Is there a contrast in the MS between p molle and the standard p?

**Comment by psb1558** [comment]
Here's a bit of a change for l + loop, which was too easy to mistake for a form of long s or f:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/16215767/186157275-6b5130e6-2120-4ad1-9f98-5da6b88ece40.png">

**Comment by jsbien** [comment]
> Is there a contrast in the MS between p molle and the standard p?

You can find in my old comment above two instances of p in Latin words: Topicorum, exempla. For me they look more like p durum. I will search for more examples later.

> Here's a bit of a change for l + loop

It's OK for me.

**Comment by jsbien** [comment]
Examples of the standard p:
First scribe:
![privato](https://user-images.githubusercontent.com/8024702/186170879-c50dc4ed-3c98-43f0-9a91-d1ac31cb6cc7.png)
![pars](https://user-images.githubusercontent.com/8024702/186170928-30dd9659-57a6-43a4-8358-5cdd564d9bb1.png)
![republica](https://user-images.githubusercontent.com/8024702/186170954-8129c84d-64cb-4861-8d88-00202d5d8bbe.png)
Second scribe:
![2optinere](https://user-images.githubusercontent.com/8024702/186171029-da917b8b-71c6-4232-b91d-dca1dc42b704.png)
![2positum](https://user-images.githubusercontent.com/8024702/186171067-745a7097-6aa7-4b3c-80a2-be7311d53372.png)
![2simplex](https://user-images.githubusercontent.com/8024702/186171089-e9fdeac6-9101-4ecd-b7da-7dda8ea5aaa6.png)

**Comment by psb1558** [comment]
Okay, I see it (I think). He's exaggerating the roundness of p molle and omitting the top of the left-hand vertical stroke. Makes it look a little like a Greek rho. From MS p. 6:
<img width="519" alt="image" src="https://user-images.githubusercontent.com/16215767/186217972-3229293d-08b8-4b14-aeb9-d74c1e8724bd.png">
Exaggerating the roundness won't work very well when the bowl of the Junicode p is already round, but we can certainly omit the top of the right-hand stem:
<img width="219" alt="image" src="https://user-images.githubusercontent.com/16215767/186220400-2a62bcd0-678f-4577-88f0-b47104a449a4.png">

**Comment by psb1558** [comment]
It's possible to subtly emphasize the quadness of the quadrata letters by making one side of the bowl a little concave:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/16215767/186225321-86489f8f-0f99-4a17-be59-3d670f2de2f3.png">

**Comment by psb1558** [comment]
Sorry, I got the wrong b in that last screencap:
<img width="189" alt="image" src="https://user-images.githubusercontent.com/16215767/186226294-20e9bbca-5d9f-4bf6-b0cd-e830a35640aa.png">

**Comment by psb1558** [comment]
I've made the tail of this alternate g a bit less extravagant to reduce the danger of collisions.
<img width="140" alt="image" src="https://user-images.githubusercontent.com/16215767/186227998-cb583d4b-1e7a-4b27-a171-b69d8b259d92.png">

**Comment by jsbien** [comment]
> t's possible to subtly emphasize the quadness of the quadrata letters by making one side of the bowl a little concave:

Looks nice.
Alternate g is also OK.

**Comment by psb1558** [comment]
Okay. The roman version of the font (I'll add italics eventually) now has what I hope is a complete collection of Parkosz's special phonetic characters:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/16215767/186246954-605bfe67-fd75-4b36-bb7f-b3241c8532e0.png">
The existing tags in Junicode are listed in ch. 5 of the Junicode Manual. There you can see that a character is always defined by a sequence of **base character + two tags**. The font contains tags for a-z and 0-9 (plus a special "cancel" tag). I have no objection in principle to adding other tags, but it seems unnecessary in this case, since none of the present two-tag sequences begins with p.

For base characters I very strongly prefer the most common possible alphabetic characters rather than IPA or other exotics. This is for accessbility, ease of use, and the searchability of text; also because the tagged characters have got to be duplicated in the cvNN feature set, and there is no room in the set for new base characters.

One could simply use the tags to number the variants, but I prefer mnemonics where possible. So I'd suggest a series of base+tag sequences looking like this:

`b&__p;&__s;` b square
`b&__p;&__l;` b with loop
`c&__p;&__h;` c with hook
`g&__p;&__h;` g with hook
`l&__p;&__l;` l with loop
`p&__p;&__r;` p round
`p&__p;&__s;` p square
`v&__p;&__h;` v with hook

By the way, these characters strike me as good candidates for Unicode encoding. I'm thinking of the recent additions of characters from another early work with great importance for the history of a particular language: the 12th c. Middle English *Ormulum*, which is analogous to Parkosz's work in a number of ways. I wonder if Michael Everson would be interested in helping to work up a proposal.

**Comment by psb1558** [comment]
I should add that it might be desirable to have "p" tags for characters in Parkosz that are already in Junicode and accessible via other tags: m with descender (MUFI U+F223), n with descender (MUFI U+F228), perhaps others.

**Comment by psb1558** [comment]
Italics.
<img width="358" alt="image" src="https://user-images.githubusercontent.com/16215767/186312296-33b3b56c-a60e-4a60-906f-fffa40362601.png">

**Comment by jsbien** [comment]
Italics OK.
> I should add that it might be desirable to have "p" tags for characters in Parkosz that are already in Junicode and accessible via other tags: m with descender (MUFI U+F223), n with descender (MUFI U+F228

I fully agree.

**Comment by psb1558** [comment]
Are majuscules required for all the characters?

**Comment by jsbien** [comment]
No. In my note I listed those really used.

**Comment by jsbien** [comment]
As for #24, ss will be 09 as mentioned there? What about PLK value? Is it still needed?

**Comment by psb1558** [comment]
I forgot about the "Majuscules" section of your paper.

Are these (on p. 6) fair examples of capital P molle and P grossum?
<img width="297" alt="image" src="https://user-images.githubusercontent.com/16215767/186401097-5ed6ef14-b99e-4335-ada6-89f386e6ce8b.png">

**Comment by psb1558** [comment]
ss09 is still reserved for language-specific variants, though there aren't any yet (in Elstob I'm using it for Vietnamese and English). But ss09 is most appropriate for variants that are purely stylistic (these are substantive). Also, since the tag sequence is unique, there's no need for a language-specific feature in the font: the tags will do it without the added complication.

Yes, just ss10 to activate the tags.

**Comment by psb1558** [comment]
Do any of these letters ever take diacritics?

**Comment by jsbien** [comment]
No diacritics.
Difficult to say which examples of capital are best, especially as there are two scribes. Below are examples from the largest sample of the Polish text (last but one page).
![Pissoc](https://user-images.githubusercontent.com/8024702/186410017-b170d004-0c2d-4755-b383-fd951cc993e9.png)
![Patrzy](https://user-images.githubusercontent.com/8024702/186410054-7f86c845-786a-498f-98fd-485bf8b0bbf9.png)
![Pisch](https://user-images.githubusercontent.com/8024702/186410148-02e1c3b4-4d63-4178-a269-05ffdd41660b.png)
![P1issem](https://user-images.githubusercontent.com/8024702/186410110-d331e68d-788b-4df4-89d8-9a3039e3670d.png)
![Boc](https://user-images.githubusercontent.com/8024702/186410083-32b343b4-e8c6-4133-80ac-5277d2c4b18a.png)
According to Kucała's interpretation all P are capital, the last one is P molle. The interpretation is said to correct scribe error, so in practice you can't take it for granted.

**Comment by psb1558** [comment]
Capitals.
<img width="130" alt="image" src="https://user-images.githubusercontent.com/16215767/186414839-35db3a26-2f87-4961-9a41-2ddb1a6c20c4.png">

**Comment by jsbien** [comment]
OK

**Comment by psb1558** [comment]
The new characters and features are in the current build: 1.052beta. Grab the font, try it out, and let me know how it works. There is a little doc, [Parkosz_tags.pdf](https://github.com/psb1558/Junicode-font/blob/master/docs/Parkosz_tags.pdf), listing the new tags. In the Parkosz tag sequences, the first tag is always **p**, and the second is meant to be mnemonic. The second tag in any of the sequences can be changed if you like.

**Comment by jsbien** [comment]
Thank you very much once again! I've just tested the font with my TUGboat paper and noticed no problems. We can assume everything is OK.
For completeness, I would appreciate G p d sequence to access G with dot above.

**Comment by psb1558** [comment]
I have added the G p d sequence, and it will be in the next build (1.053).

**Comment by jsbien** [comment]
Thanks!

**Comment by psb1558** [comment]
I think this is done now.

**Comment by mbudaj** [comment]
Hi, this is a great addition; very useful for old Czech prints, too.

However, I encountered a problem with _b with loop_ and _l with loop_ if they follow _ſ_ (long s) character. In this case a standard ligature is built (_ſb_ or _ſl_) and the loop is lost. This occurs in both LuaTeX v1.15 and OpenOffice Writer v7.4.4.2 (looped characters and entered using unicode tags and ss10 stylistic set is applied to the whole document).

![image](https://user-images.githubusercontent.com/10212561/212482382-fb59ca10-44b1-4733-88af-269e0846b218.png)

Could you either 
- add special ligatures of _ſ_ or _ſſ_ with looped _b_ and _l_, or 
- prevent building of _ſb_ or _ſl_ ligatures in the case of looped _b_ and _l_?

(In addition, could _ſł_ and _ſſł_ ligatures by added to the font as well?)

**Comment by psb1558** [comment]
The ligatures are being built before looped b and l are substituted for plain b and l. I can't change the order of lookups without breaking other things. Maybe I'll think up a solution for this particular case in time, but for now just place a zero-width non-joinger (U+200C) between the s and the b or l.
<img width="80" alt="image" src="https://user-images.githubusercontent.com/16215767/224136343-a3d02ef1-e14a-4578-83c4-b2dc407f620c.png">
The business with longs + lslash is much simpler: this will happen invisibly when calt and ss08 are enabled:
<img width="92" alt="image" src="https://user-images.githubusercontent.com/16215767/224141185-d39dead3-4962-4a65-9ee7-52e81f3cd1cb.png">

**Comment by psb1558** [comment]
Italic:
<img width="124" alt="image" src="https://user-images.githubusercontent.com/16215767/224147997-da46effd-b1ae-41bd-8efb-356cd3821dc8.png">

**Comment by mbudaj** [comment]
Thanks!
