### ISSUE TITLE
adding text-critical symbols

### ISSUE THREAD

**Issue by mbudaj** [psb1558/Junicode-font#271]
Hi,

would it be possible to add editorial symbols (2E00–2E0D Unicode range) used in some critical editons, especially Novum Testamentum Graece? Their traditional appearance is like this:

![SQE15](https://github.com/psb1558/Junicode-font/assets/10212561/3d2ea67c-a93b-4d47-b84c-50306f5b0005)

In the continuous text, with some numerals added:

![image](https://github.com/psb1558/Junicode-font/assets/10212561/1800a814-1aa8-423e-a566-9631eb30a38d)

In italics:

![image](https://github.com/psb1558/Junicode-font/assets/10212561/70ccdfb8-6c13-4eb2-a31a-549403aa1948)

Their support in various fonts is mostly insufficient:

![image](https://github.com/psb1558/Junicode-font/assets/10212561/6cd0d27f-4434-4300-b1ed-85c8c90a9c05)

Only Apparatus SIL (designed specifically for this purpose) and Brill come close. For other fonts, even if they contain the characters, their shape is inadequate (see the guidelines below).

Would it be possible to add them to Junicode? I tried to compile the basic guidelines here:
- they should resemble a technical drawing (like math symbols); there should be no fancy strokes like in Alphabetum
- the shape should be the same in roman and italics styles (no slanting)
- their height should match
- the special cases are ° and ˸ as there are no special slots for them. Probably character variants of the degree symbol (00B0) and raised colon (02F8) would be the best solution 
- their height should fit also optionally added superscript numerals (either the same size or reasonably aligned)

Additional background information on the symbols themselves is in the [old proposal](https://www.unicode.org/L2/L2002/02317r-tlg-ntsigla.pdf) for their inclusion into Unicode.

**Comment by psb1558** [comment]
This seems a very good idea. I'll work on it.

**Comment by psb1558** [comment]
Here's a first go. Comment?

**Comment by mbudaj** [comment]
Thanks! 

In all printed samples I've seen (various editions of Novum Testamentum Graece and Synopsis Quattuor Evangeliorum) there are actually no differences in stroke widths for vertical/horizontal/oblique strokes. But perhaps this style fits the spirit of Junicode better and would serve as good as uniform strokes.

For ⸁ ⸄ ⸅ I'd suggest to move the dot a bit closer to the main shape.

It seems that ⸀and ⸁ have different heights. Also, ⸌ and ⸍ are shifted higher than the others.

For ⸌ and ⸍ I suggest to draw them at 45 degrees angle as is the case in printed editions.

**Comment by psb1558** [comment]
Here's another go. For ⸁ and the like, I've centered the dots vertically and allowed about a stem's worth of space between the vertical stem and the dot. Overall, I've tried to make the stem widths all the same (though the s-like figures still look a little light) and make all the signs take up the same amount of vertical space.

<img width="439" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/7d3e0609-acfe-4ee7-b980-9ef644b3e290">

If you've got a bit of Unicode-encoded text to share, we can see more of what they'll look like in context.

**Comment by psb1558** [comment]
Do you use a degree sign for the "verbum sequens omittitur" symbol?

**Comment by psb1558** [comment]
Found some text for testing.

<img width="1067" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/9b42acda-4758-411b-a421-43957bd626a5">

**Comment by mbudaj** [comment]
It looks great! Thank you.

For ° and ˸ the degree symbol (00B0) and raised colon (02F8) should be used, possibly having the right shape as a CV alternative.

How would the symbols combine with superscript numerals?

**Comment by psb1558** [comment]
I'm glad you asked, because I had forgotten that bit and had to make an adjustment to the vertical position of the editorial marks. They will work well with the default figures (I suggest applying ss09 to the whole text for clarity:
<img width="288" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/268fe48c-7974-4a4b-8210-0dfb1c172392">
Position will be a little less optimal, but still okay, I think, with lining/tabular superscripts:
<img width="317" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/17c52bcf-1d9f-4121-9e2e-105e99ec3dea">
I have one cvNN feature left unused: I can use it for this, or (breaking the rules a little less), my last Stylistic Set (ss11).

**Comment by psb1558** [comment]
U+02F8 is a mod character but was not scaled or positioned properly. I've corrected it, and it should work for you. The alt degree sign (I'm labeling it "Word omitted sign") will be on cv99.
<img width="369" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/59ad01df-d49d-4ae2-929b-eeed31b0c1f7">
If this is okay, I'll copy these signs to the italic face, do various fixups, and release a new version (probably next week sometime).

**Comment by mbudaj** [comment]
It's excellent, I've no further comments. Thank you.

**Comment by psb1558** [comment]
Okay. I'll close this when the next release is ready.

**Comment by psb1558** [comment]
Version 2.207 is out now, with these glyphs in it, and I am closing this as complete.
