### ISSUE TITLE
Request for some «diamonds» and «lozenges»

### ISSUE THREAD

**Issue by theblursed** [psb1558/Junicode-font#272]
Dear psb1558,

I'm writing you again for a new proposal. This time a simple thing which requires not a lot of explanation: the addition of the `◇`, `◆`, `⬦`, `⬥`, `♢`, `♦︎`, `❖`, `🞙`, and `⬩` characters to Junicode; or at least `◇` and `◆`.

For me, and probably other linguistics writers/typesetters, they would be useful as symbols and separators in glossaries, dictionaries and the like.

More precisely:

1. ◇ — white diamond — U+25C7
2. ◆ — black diamond — U+25C6
3. ⬦ — white medium diamond — U+2B26
4. ⬥ — black medium diamond — U+2B25
5. ♢ — white diamond suit — U+2662
6. ♦ — black diamond suit — U+2666
7. ❖ — black diamond minus white X — U+2756
8. 🞙 — black medium small diamond — U+1F799
9. ⬩ — black small diamond — U+2B29

Thank you for anything and have a good weekend

**Comment by eclecticfluff** [comment]
There′s no need to co-opt playing card suits for the lozenges as Unicode already incudes a series of lozenges  characters.
◊ — lozenge — U+25CA
⧫ — black lozenge — U+29EB
⬨  — white medium lozenge — U+2B28
⬧  — black medium lozenge — U+2B27
⬫  — white small lozenge — U+2B2B
⬪  — black small lozenge — U+2B2A
🞠 — white lozenge containing small black lozenge — U+1F7A0
There are some more I didn′t list, but at some point it feels excessive. I doubt there′s much practical use for six sizes of black lozenge.

**Comment by theblursed** [comment]
Thank you @eclecticfluff, I didn't know those existed. 🙂 It may anyway be noted, for aesthetic and compatibility purposes, that fonts that have both characters (at least the fonts I have in my computer) use notably different shapes for them, with the proper lozenges being "sharper", thinner and/or taller:
![Schermata 2024-04-19 alle 08 58 26](https://github.com/psb1558/Junicode-font/assets/134559730/3dba9ed4-cb9d-4edf-b6a5-375290b60abc)

**Comment by psb1558** [comment]
I have added 2B25, 2B26, 25C6, and 25C7.

**Comment by theblursed** [comment]
Thank you! You're always very kind 😊

**Comment by psb1558** [comment]
Version 2.207 is out, with the diamond glyphs in it, and I am closing this as complete.
