### ISSUE TITLE
MUFI 00F4E8 LATIN SMALL LIGATURE LONG S L WITH DIAGONAL STROKE

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#273]
I just noticed that the character, proposed by me some time ago and accepted, is described now (https://mufi.info/q.php?p=mufi/chars/unichar/62696) as "Incorrectly encoded at some point" and "deprecated".

It was and is needed for Polish, at least in principle (I guess nobody used it except myself). Unfortunately it seems my original proposal is no longer on the MUFI site, but I will try to reconstruct it, the examples were from the IMPACT corpus (https://szukajwslownikach.uw.edu.pl/).

I will appreciate if you include it in some way in Junicode; sticking to the original MUFI code point is not necessary.

**Comment by jsbien** [comment]
In https://www.researchgate.net/publication/351121973 I state that the character occur over 8 thousand times in the corpus, but also contribute to the mess calling it just LATIN SMALL LIGATURE LONG S L WITH STROKE. It was encoded than as U+F51E. I think the query  `"\uF51E"/i` should find its occurences in the corpus but it does not :-( So I cannot provide the examples as quickly as I would like, but I will work on it.

**Comment by psb1558** [comment]
If this is what I think it is, it turned up in the MUFI materials without an illustration, and I didn't know quite what to make of it. But I see now that it was a thing that Junicode already had as a Contextual Alternates (calt) rule substituting combining forms of **ſ** and **ł**:
<img width="177" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/988d5201-f048-4cf6-89cd-53dd4c67bbf6">
In general it is not necessary to encode ligatures, at least when they're handled by "always-on" features like calt and liga. But of course I will encode it if you can work the matter out with the MUFI folks.

**Comment by psb1558** [comment]
ſ and ł should ligature whenever they occur together, but if it doesn't work, just turn on `calt` when you load the font with fontspec:
```
\setmainfont{Junicode}[Alternates=Contextual]
```
Or if you're using the new `junicode` package in CTAN:
```
\usepackage[MainFeatures={Alternates=Contextual}]{junicode}
```

**Comment by jsbien** [comment]
You right, it is ligated. Thanks!

**Comment by jsbien** [comment]
Are you on the mufi-fonts list? Tarrin Jon Wills just wrote

> It's at F4F8 (cf. AndronScriptor), not F4E8. I've left the latter also in the database for clarification in case there are references to the incorrect codepoint. But
please let me know if I have misunderstood something and it should in fact be at F4E8 (and Andreas's mistake?). 

What is you opinion?

**Comment by psb1558** [comment]
Well all the other U+F4FN characters are ligatures, so I suppose U+F4F8 is as good a place as any. I will add it. But I strongly discourage the use of PUA code points for ligatures when OpenType features can do the job in a more convenient and accessible way.

**Comment by jsbien** [comment]
I think it is worth adding just for the compatibility with MUFI. Thanks!

**Comment by jsbien** [comment]
I'm confused :-( In version 2.208 there is neither F4E8 nor F4F8. I don't really need it,  I just picked up the character to illustrate the MUFI recommendation and junicode in a presentation. I can of course use another character, but I'm just curious...

**Comment by psb1558** [comment]
I've added it.

**Comment by jsbien** [comment]
OK, the presentation is planned for October :-)

**Comment by psb1558** [comment]
It should be before that.
