### ISSUE TITLE
Hi - could I please request that the extended tail form also be added for small caps?

### ISSUE THREAD

**Issue by dhinostroza** [psb1558/Junicode-font#276]
Hi - could I please request that the extended tail form also be added for small caps?
![image](https://user-images.githubusercontent.com/6895210/159480639-e1d3b543-c41c-4cf9-9985-7c940800edc3.png)

_Originally posted by @TheKnightWho in https://github.com/psb1558/Junicode-font/discussions/72#discussioncomment-2414361_

I also need this.

**Comment by psb1558** [comment]
I've got a pretty long to do list right now, but I'll add these when I can.

**Comment by psb1558** [comment]
This is done, and will be in the next release (2.07). There are two ways to get these shapes of small cap q.

1. Q + cv33[3] or cv33[4] + c2sc.

2. q + cv34[3] or cv34[4] + smcp.

**Comment by psb1558** [comment]
Version 2.207 is out, and this issue is complete.
