### ISSUE TITLE
Ligature for tf desirable

### ISSUE THREAD

**Issue by RDHWalker** [psb1558/Junicode-font#277]
Although there are ligatures available for ff and ft, the combination tf does not have a ligature defined, and the combination looks awkward (in italic style). See screen-shot.
![ligature tf needed](https://github.com/psb1558/Junicode-font/assets/101460176/0aa3d717-0bdb-4ca3-9a52-7cd27761ae02)

**Comment by psb1558** [comment]
Ligatures don't generally form across boundaries between compound elements, word roots and suffixes, and the like. In English, at least, that's the only kind of environment the sequence tf occurs in, and in the other languages I know it's not much different. That, I suspect, is why that ligature doesn't occur in the other big fonts I know. Are you working with a language with a different situation?

**Comment by RDHWalker** [comment]
OK. This combination came to my attention in a proper name: Stratford. I agree that a ligature itself is not necessary, but the awkwardness remains of a different height for the cross-bars in adjacent letters. Perhaps those two heights could be made the same?

**Comment by psb1558** [comment]
Equalizing the cross bars seems a good idea. I'll work on it.

**Comment by psb1558** [comment]
Here's the basic change:
<img width="361" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/cc4e5e1a-d54b-4e4a-a5bd-a78729c999be">
But lots of glyphs have **t** as an element, and it's going to take a while to find and fix them all.

**Comment by jcrippen** [comment]
Equalized crossbars will also help in low res contexts like thumbnails, scaled page sizes in PDF readers, etc., since they’re less likely to trigger antialiasing misbehaviour.

**Comment by psb1558** [comment]
They'll improve the hinting too.

**Comment by RDHWalker** [comment]
> Here's the basic change: 

Looking better!  Thanks.
