### ISSUE TITLE
Ь and ъ in kursive

### ISSUE THREAD

**Issue by indoger1** [psb1558/Junicode-font#278]
The font in general is great. We stumbled just upon one issue, that is important for us since we work a lot with Slavonic etyma. Ь and ъ seems to be missing (only) in kursive (see attached images). Can this be fixed?
![image001](https://github.com/psb1558/Junicode-font/assets/58651570/e08f6b60-ae9b-4c41-bfca-ce55304819d4)

**Comment by psb1558** [comment]
What version of Junicode are you using, and is it the ttf, otf, or variable flavor?

**Comment by psb1558** [comment]
Also: I don't know about your system or software, but make sure you don't have an older version of Junicode installed alongside the latest version.

**Comment by indoger1** [comment]
Dear Peter,
Thanks for the tips! I have to apologize we didn't try enough to fix the problem ourselves. I can't tell you what exactly was the problem but after complete removal of all (old) fonts and reinstallation everything works fine!
Thanks and again, great font!
Best
Gerhard

__________________________
Dr. Gerhard Rampl
Department of Linguistics
Coordinator of the University exchange UNO - UIBK
University of Innsbruck

On May 15, 2024 16:51, Peter Baker ***@***.***> wrote:

Also: I don't know about your system or software, but make sure you don't have an older version of Junicode installed alongside the latest version.

**Comment by psb1558** [comment]
I'm very glad you got the hard and soft glyphs and that the font is working out for you.
