### ISSUE TITLE
An idea for B with flourish

### ISSUE THREAD

**Issue by tommai4881** [psb1558/Junicode-font#279]
Please add b with flourish (Ꞗꞗ; U+A796 and U+A797)

**Comment by psb1558** [comment]
These will be in version 2.07 (coming soon).
<img width="115" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/adfd3871-34fb-4dd7-a4c3-0f124fd5f11a">

**Comment by psb1558** [comment]
Version 2.207 is out, and this is complete.
