### ISSUE TITLE
Request for a few characters

### ISSUE THREAD

**Issue by felileg** [psb1558/Junicode-font#283]
Hello!

I'm digitizing some old dialectological sources and would like to suggest the addition of a few characters that are used a lot in them (pre-IPA phonetic characters):

- ꞓ - Latin Small Letter C with Bar
- ₔ - Latin Subscript Small Letter Schwa

They have a fairly classic shape and shouldn't pose any problems.

Thank you for your amazing work!

**Comment by psb1558** [comment]
This is done and will be in the next release (whenever that is).

**Comment by psb1558** [comment]
Version 2.209 now released, and I am closing this.
