### ISSUE TITLE
cv89 doesn’t work with b

### ISSUE THREAD

**Issue by silmeth** [psb1558/Junicode-font#286]
When trying to use `cv89` (character variant which places a dot above the combining overline u+0301 diacritic), it doesn’t work if it’s placed over the letter b (but works eg. with a).

![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/d265ee07-5b48-4697-80e3-ad08bdf390c4)

That’s annoying for Irish where *b* + overline / suspension stroke above it + lenition dot is a fairly common combination.

Doing b + combining overline + combining dot above doesn’t produce the desired output either:
![obraz](https://github.com/psb1558/Junicode-font/assets/5329644/856d9e54-e1e1-40a5-8be5-b8bac23056ec)

(I’d expect the dot to be placed above the line)

**Comment by psb1558** [comment]
I've added an anchor so that (after the next release) the sequence **b U+0305 U+0307** will produce the effect you want. I'll see if I can make cv89 work too, before the next release.

**Comment by psb1558** [comment]
Version 2.209 released. Closing this now.
