### ISSUE TITLE
Different documentation for JunicodeVF and Junicode

### ISSUE THREAD

**Issue by Doc73** [psb1558/Junicode-font#290]
Dear Prof,
I just noticed that
```
texdoc junicode
```
opens `JunicodeManual.pdf` for **version 2.209**, but
```
texdoc junicodevf
```
the same manual for **version 2.206**.

I would suggest, if possible, to unify the documentation.

Many thanks and best regards,
Domenico Cufalo

**Comment by psb1558** [comment]
I don't do the packaging for CTAN, but I'll pass this along to the person who does. Since nothing else can be done about it here, I'll close this now.
