### ISSUE TITLE
Contextual long ess with variant

### ISSUE THREAD

**Issue by bryankaplan** [psb1558/Junicode-font#294]
Is it possible to retain contextual the logic of `ss08` (contextual long ess) when specifying a `cv38` variant? If so, how?

Currently, I observe specification of `cv38` causes the selected long ess variant to replace all esses, irrespective of their location, even when `ss08` has been selected too.

**Comment by psb1558** [comment]
`ss08` and `cv38` aren't meant to be used together. Use `ss08` when you want long s to vary with round s contextually, and `cv38` when you want long s (or some other variant of s) everywhere. Junicode only varies s and long s (U+017F) contextually--not other variants of s--and only in English, French, and Latin.

**Comment by psb1558** [comment]
I actually thought about this when I was setting up the OT features for s. `ss08` is for reproducing the practices of early printers in English, French and Latin: it's a one-stop for that purpose, and nothing else is needed. The primary purpose of `cv38[3]` is to handle texts where long s is not contextual--for example, a diplomatic transcript of a manuscript in Carolingian minuscule. I don't see what purpose would be served by making the two features work differently. If you want to do something that you can't currently do, let me know and I'll give it some thought.

`cv38[3]` can be used with `ss08` in one way that I forgot about when replying to your first post: it *reverses the effect* of `ss08`:
<img width="354" alt="image" src="https://github.com/user-attachments/assets/34677e09-6b55-4bee-bede-21288aebd48c">
This can be useful when an early printed text contains exceptions to the usual rules.

**Comment by bryankaplan** [comment]
I was asking about `4` & `12`, yet you answered about `3`. While that's a bit confusing, thank you for documenting the reversal effect. You might want to add a note about it to the official docs, as it's potentially useful.

I realized that `ss08` renders contextual long esses with descenders automatically in italics.

I still think it would be swell if `cv38[4]` & `cv38[12]` were compatible with `ss08`, but the fact that italics renders with descenders is all I really needed to understand.

**Comment by psb1558** [comment]
Sorry, I've been thickheaded, somehow missing a big part of your request, that you are asking to add contextual behavior for particular long s variants. I can look into whether this can be done without making a mess. Are you thinking of this for a particular project?

**Comment by bryankaplan** [comment]
We're all guilty of occasional thickheadedness. I forgive you!

Honestly my current use-case is assuaged by the fact that descenders appear in italics.

I do think it would be good and sensible for long ess variants `cv38[4]` & `cv38[12]` to get contextual behavior when `ss08` is active, but at this point my personal interest in that goal is theoretical.

If indeed it can be done without making  mess, please reopen this issue. Thank you for looking into it!
