### ISSUE TITLE
Add wynn (Ƿƿ) as separate variants of Ww

### ISSUE THREAD

**Issue by shadowdragon625** [psb1558/Junicode-font#304]
I absolutely love this font but what bugs me is that wynn is only available with insular letter-forms active; I don't like the insular R and insular S characters very much (imo) for my writing projects. They look awesome though!

But I only want wynn :C 

Is there a way such that wynn can be only a separate variant of Latin W?

**Comment by psb1558** [comment]
I suppose I could add them to cv45 and cv46, if that would help. And of course you can just use the code points U+01F7 and U+01BF.

**Comment by shadowdragon625** [comment]
Apologies for the late reply, thank you for your response!

Whatever is more convenient, cv45 and cv46 could work fine like where the Anglicana W is located.

But for now I'll stick with the unicode characters, thank you again for your input ^^

**Comment by psb1558** [comment]
I'm glad the code points will do for you.
