### ISSUE TITLE
Incompatability at intersection of `junicode`, `selnolig`, and `biblatex`

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Junicode-font#310]
I am not sure this is a problem with `junicode`, `selnolig`, `biblatex`, or `fontspec`, but after some preliminary testing, the former seems most likely to be broken. The gist of the issue appears to be that `selnolig` errors on `biblatex`'s field format specification when `fontspec` changes font features given the setup in `junicode`. The minimal working example I have been testing with is as follows,
```latex
% !TeX TXS-program:compile = txs:///lualatex/[-verbose --halt-on-error]
\documentclass{article}
\begin{filecontents*}{\jobname.bib}
	@ARTICLE{greenwade93,
		author  = "George Greenwade",
		title   = "The {C}omprehensive {T}ex {A}rchive {N}etwork ({CTAN})",
		year    = "1993",
		journal = "TUGBoat",
		volume  = "14",
		number  = "3",
		pages   = "342--351"
	}
\end{filecontents*}

%%Working font setup
%\usepackage{fontspec}
%\setmainfont{junicode}[Numbers=OldStyle]

%Broken font setup
\usepackage{junicode}

\usepackage[english]{selnolig}

\usepackage[style=numeric,backend=biber]{biblatex}
\addbibresource{\jobname.bib}

%Formatting that breaks selnolig/junicode
\DeclareFieldFormat{labelnumber}{\addfontfeature{Numbers=Lining}#1}

\listfiles
\begin{document}
	\cite{greenwade93}
	\printbibliography
\end{document}
```
I am using the following setup and package versions:
- LuaHBTeX, Version 1.18.0
- Biber 2.20
- TeX Live 2024
- junicode 2024/06/06
- selnolig, Version 0.333
- biblatex 2024/03/21 v3.20
- [complete log file](https://github.com/user-attachments/files/18188546/test.log)

Note that the `selnolig` version I am using is the latest from its github and not CTAN. I went through the hassle of manually changing versions in hopes that it would rectify this problem, but not dice.

**Comment by psb1558** [comment]
For anyone looking on: the test file produces this error:
```
warning  (ligkern): error: ...xlive/2024/texmf-dist/tex/lualatex/selnolig/selno
lig.lua:134: bad argument #1 to 'char' (invalid value)
.
\@item ...hbox to\labelwidth {\unhbox \@tempboxa }
                                                  \fi \hskip \labelsep }\ign...
```
The only thing I can think of that might cause a problem like this is some incompatibility between `junicode.sty` and one of the `.sty` files for biblatex or selnolig, causing a bad value to be passed to selnolig's Lua code. Perhaps a name clash. I'll investigate that (though I made the names in `junicode.sty` rather elaborate so as to avoid name clashes) and whatever else I can think of. Meanwhile, I'm glad that you have a workaround.

**Comment by eclecticfluff** [comment]
After doing some proper testing, commenting out lines of the .sty trying to figure out what precisely makes compilation fail, the plot thickens. For some reason, `\setmainfont{junicode}[Renderer=HarfBuzz]` is what's causing this fail. The most puzzling thing is that other font's I've tried including Times New Roman and Segoe UI Variable work perfectly fine in the same environment with HarfBuzz.

**Comment by eclecticfluff** [comment]
Further searching has turned up [this](https://tex.stackexchange.com/questions/571106/selnolig-turns-en-and-em-dashes-into-hyphens-if-polyglossia-is-loaded-before-the) tex.se issue, so it seems like the incompatibility is a known problem despite not (to my knowledge) being reported anywhere before now.

**Comment by eclecticfluff** [comment]
Checking over the package details, would it be possible to add a package option labeled something like ``Renderer=Compatibility'' to force the `XeTeX` font loading commands even when running with `LuaTeX`?

**Comment by psb1558** [comment]
I've added an option to both the junicode and junicodevf packages: **renderer** (lowercase to match the usage of other options), with which you can choose Node or any other renderer supported by fontspec (this is passed straight through to fontspec).

I suspect that Node will cause problems with the variable font—documents may fail to compile. Not so much with the static font, where Node may handle some OpenType features incorrectly (but I haven't tested in a few years—maybe these problems have been fixed). But of course, you can choose any other renderer, not just Node. The default remains HarfBuzz.

**Comment by psb1558** [comment]
I think we've gotten to the bottom of this now.

**Comment by eclecticfluff** [comment]
I’m not at my computer to make a pull request now, but I experienced an error trying to use use any renderer except HarfBuzz or OpenType and traced it to incorrect bracing on the `\textEnlargedMinuscules` macro definition. I have no idea why it only shows up as a compilation error when changing renderer.

**Comment by psb1558** [comment]
Thanks for the pull request, @eclecticfluff! It seems to be working perfectly now.
