### ISSUE TITLE
Feature Request: `case` OpenType Feature

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Junicode-font#312]
Considering the other typographical niceties provided and planned for junicode, I hope it isn't too much to ask that support for the `case` feature be added. While I don't have any examples of fonts that implement it on hand, the explanation from [Microsoft](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-case) seems clear enough.

**Comment by psb1558** [comment]
I don't understand. Junicode already has a `case` feature. See p. 18 of the Junicode Manual.

**Comment by eclecticfluff** [comment]
Sorry, I must have missed it. I could have sworn it wasn't there last I checked.

**Comment by eclecticfluff** [comment]
Shoot, forgot how github closing issues worked again. Anyways, sorry for forgetting about it in the manual. I was more interested for its use with harmonizing punctuation with runs of capital text, e.g. for bracketed number citations like [1]. Also, from the manual and OpenType details, it seems that the feature should automatically enable lining numbers, but at least with the LaTeX package it does not.

**Comment by eclecticfluff** [comment]
Here's a crude example of what I was thinking of using `\raisbox{0.1ex}`
![{960E9EA3-6DCF-4797-A1C2-50D8D636B055}](https://github.com/user-attachments/assets/dd8f5de1-ece5-4302-be79-11a14ad38620)

**Comment by psb1558** [comment]
Right now case only works with diacritics, though I know a number of fonts use it for punctuation that harmonizes with caps. I'll look into that.

I'll try to figure out why numbers aren't being changed in LaTeX. They are working elsewhere.

**Comment by kenmcd** [comment]
Junicode only has the lining figures in user-facing `case`.
Most common user-facing `case` features are punctuation.
Such as: ()[]{}-–—\|/@‹›«»·•¿¡

/parenleft/parenright/bracketleft/bracketright/braceleft/braceright/hyphenminus/endash/emdash/backslash/bar/slash/at/guilsinglleft/guilsinglright/guillemetleft/guillemetright/periodcentered/bullet/questiondown/exclamdown

These move up a little bit to better align with the uppercase letters.
This is some punctuation from Spectral:
![case Spectral 2024-12-19_10-32-57](https://github.com/user-attachments/assets/5364e36a-dbf5-47d4-9a4c-c382ad8c32de)

Also common to have `#` and currency signs.
Junicode only has `$` right now.

**Comment by khaledhosny** [comment]
It might be possible/easier to implment this feature with GPOS single pos adjustment moving the glyphs up. That might be the less common approach, so, as everything OpenType, some popular app somewhere might not handle it correctly.

**Comment by psb1558** [comment]
Thanks for the suggestion, @khaledhosny! Junicode already does a little bit of vertical contextual kerning, and I've found it well supported, so that's the direction I'll try.

**Comment by eclecticfluff** [comment]
IIRC, Junicode already uses GPOS so much that it causes issues with running Glyphs. The font’s size and complexity already makes it an stress-test of font technology across programs anyways. With that said, if it’s possible to use GPOS for the feature, potential incompatibilities are probably fine. I doubt most people interested in `case` would want to use it in a program without other advanced features for micro-typography, and such a program doubtless has better font support than MS Word.

**Comment by psb1558** [comment]
This is going well so far:
<img width="529" alt="image" src="https://github.com/user-attachments/assets/4fe6892b-6345-4adb-a029-004931a60785" />

**Comment by psb1558** [comment]
@kenmcd: numbersign and the currency signs were on the number features (`pnum`, etc.), but I've added them to `case` as well. Thanks for pointing this out!

**Comment by eclecticfluff** [comment]
It looks perfect so far. Another possible addition, while not strictly necessary, is the old higher quotation marks. They looked good adjacent capitals, so I hope it isn’t too much trouble to add them back for `case`.

**Comment by psb1558** [comment]
I don't know about the quotation marks. I lowered them because I didn't like the way they sat relative to either the upper or lowercase, and when I load up Junicode 1, I still don't like the old higher position much.

**Comment by psb1558** [comment]
Done now. Watch for the next release.

**Comment by kenmcd** [comment]
@psb1558  Realized I forgot /backslash (`005C`) in my list above.
It is in the demo GIF.
You can see this in `case` in Spectral and Calibri (on Windows) for example.
Just wanted to make sure you took a look at possibly including it.

**Comment by psb1558** [comment]
Oversight. I also forgot dashes and hyphens between lining numbers. I guess there'll be another release before long (sigh).
