### ISSUE TITLE
Semi-expanded petite capital A is malformed in all weights for variable font

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Junicode-font#313]
I have tested in both LibreOffice Writer and LuaLaTeX, with similar results in both. I have created a [test pdf](https://github.com/user-attachments/files/18214994/test.pdf) to more clearly illustrate the extent of the damage.
![test](https://github.com/user-attachments/assets/e71d87aa-b82e-4d6b-a6b8-97ba89e39b71)
```latex
% !TeX TXS-program:compile = txs:///lualatex/[--halt-on-error]
\documentclass{standalone}
\usepackage{junicodevf}
\usepackage{microtype}
\usepackage{tikz}
\usepackage{ifthen}
\usetikzlibrary{math}

\begin{document}
	\addfontfeature{Letters=PetiteCaps,Numbers=Monospaced}
	\begin{tikzpicture}[x=1em,y=1em,anchor=mid]
		\foreach \x in {0,1,...,10} {
			\tikzmath{
					integer \wid;
					\wid=\x*5+75;
				}
			\foreach \y in {0,1,...,8} {
				\tikzmath{
					integer \wgt;
					\wgt=\y*50+300;
				}
				\draw (\x,\y) node {\addfontfeature{RawAxis={Width=\wid,Weight=\wgt}}a};
				\ifthenelse{\x=10}{
					\draw[anchor=mid east] (-0.25,\y) node {\wgt};
				}{}
			}
			\draw[anchor=mid east] (\x,-0.25) node[rotate=90] {\wid};
		}
		\draw[anchor=mid]
		(-3,4) node[rotate=90] {Weight}
		(5,-3) node {Width};
	\end{tikzpicture}
\end{document}
```
(Note that generating so many font width and weight combinations slows down compilation times considerably.)

**Comment by psb1558** [comment]
Sometimes a small incompatibility between masters escapes the compatibility checks of Glyphs and fontmake, and that's what happened here. I've corrected it, and will put out a new release as soon as I've gotten through my current to-do list.

**Comment by khaledhosny** [comment]
You might find `fonttools varLib.interpolatable` quite handy for catching these kinds of compatibility issue.

**Comment by psb1558** [comment]
Thanks again, @khaledhosny. I didn't know that fonttools could do a more rigorous check: I'll try it out!

**Comment by khaledhosny** [comment]
It seems to catch this issue and a few more, here are the PDF reports for Roman and Italic from the last release: [roman.pdf](https://github.com/user-attachments/files/18216081/roman.pdf), [italic.pdf](https://github.com/user-attachments/files/18216083/italic.pdf)

**Comment by psb1558** [comment]
Whoa, that's a lot! Thanks for doing this: I'll fix these things and check out varLib.interpolatable in fonttools.

**Comment by psb1558** [comment]
These problems are all fixed now.
