### ISSUE TITLE
Feature Request: Possibility of larger smallcaps

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Junicode-font#314]
The existing small caps and petite caps aren't bad per-se, but neither size is suitable for initialisms, as demonstrated in this small example I put together.
![test](https://github.com/user-attachments/assets/574d6784-c2f6-4864-a4c4-df8fd91e390d)
Evidently, the question of how tall small cap should be in relation to their full size and petite siblings is a matter of much contention as discussed [here](https://typography.guru/forums/topic/102747-small-caps-setting-in-body-text/page/2/#comment-602300). While I will accept if you reject a fourth size for capitals as out of scope, I hope it isn't too much to ask. I imagine that a small capital height feature could not be implemented as a stylistic set due to OpenType and Glyphs limitations. However, if it were to be an axis, it could work similar to, or in fact be part of, the existing enlarge axis.

**Comment by psb1558** [comment]
Well, let's see. Junicode roman has 836 small caps, and italic has 847. Each glyph has five unique masters, so the total number of glyphs for a new set of small caps is 8,415, and I'd say that life is just too short for such a project.

But a new set of small caps isn't even necessary. Just use JunicodeVF and create a new set of small caps with a command or style that:

- scales small caps to the size you want, and
- adjusts the weight and width to compensate for the scaling.

Easy peasy!

**Comment by eclecticfluff** [comment]
Tweaking [this](https://tex.stackexchange.com/questions/691190/fontspec-separately-scale-uppercase-and-lowercase-so-tt-has-same-cap-to-x-hei) idea on tex.se, I have come up with the following functional kludge. I am posting my code here for posterity and in case anyone else want to try this. I unfortunately couldn't figure out how to get the bold weight working, but it's functional enough for my use case.
```latex
\newfontfamily{\JunSC}{JunicodeVF}[
ItalicFont =         {*-Italic},
BoldFont =           {*},
BoldItalicFont =     {*-Italic},
Renderer =           HarfBuzz,
Numbers =            {Lining},
Scale =              1.25,
Letters =            {SmallCaps,UppercaseSmallCaps},
SizeFeatures={
	{Size=-8.5     ,Weight=400,Width=115 },
	{Size=8.5 -9.5 ,Weight=382,Width=112 },
	{Size=9.5 -10.5,Weight=364,Width=109 },
	{Size=10.5-11.5,Weight=346,Width=106 },
	{Size=11.5-12.5,Weight=328,Width=103 },
	{Size=12.5-13.5,Weight=310,Width=100 },
	{Size=13.5-14.5,Weight=300,Width=99  },
	{Size=14.5-16.5,Weight=290,Width=98  },
	{Size=16.5-19.5,Weight=280,Width=97  },
	{Size=19.5-22.5,Weight=270,Width=96  },
	{Size=22.5-    ,Weight=260,Width=95  }
}
]
\ExplSyntaxOn
\NewDocumentCommand{\mytextsc}{sm}
{ \IfBooleanTF{#1}
	{ \text_map_function:nN { #2 } \__caps_to_sc:n }
	{ \text_map_function:nN { #2 } \__lower_to_sc:n }
}

\cs_new_protected:Nn \__caps_to_sc:n
{
	\str_if_eq:eeTF { #1 } { \text_uppercase:n { #1 } }
	{ #1 } { {\JunSC#1} }
}

\cs_new_protected:Nn \__lower_to_sc:n
{
\str_if_eq:eeTF { #1 } { \text_lowercase:n { #1 } }
{ #1 } { {\JunSC#1} }
}
\ExplSyntaxOff
```

**Comment by psb1558** [comment]
I don't know Expl3 at all (one of these days...). What I had in mind was just redefining one or more of the otherwise unused style definitions in the junicodevf package and using it to make an alternative small caps command:
```
\documentclass{article}

\usepackage[
  RegularFeatures={
    Letters=SmallCaps,
    Scale=1.25,},
  RegularSizeFeatures={
    {size=5,wght=350,wdth=95},}
  ]{junicodevf}

 \newcommand{\textinitsc}[1]{{\jRegular#1}}

\begin{document}
Default font: Now is the time. \textit{Now is the time.} \textbf{Now
  is the time.} \textbf{\textit{Now is the time.}}

Petite caps: {\addfontfeature{Letters=PetiteCaps}Now is the time.}

Normal small caps: \textsc{Now is the time.}

Initial small caps: \textinitsc{Now is the time.}
\end{document}
```
It yields this:
<img width="603" alt="image" src="https://github.com/user-attachments/assets/e977dafa-c074-4a7e-b792-e2c1e662e2f3" />

**Comment by eclecticfluff** [comment]
Thanks for the advice. Using the inbuilt style definition method is a lot more convenient than directly interfacing with fontspec. I've changed from growing the small caps to shrinking capitals so that figures and symbols can also be harmonized. Also, I can't say I know `expl3` properly myself. If I did, I wouldn't need to mix in `xparse` for my own addition of a starred variant.
```latex
\usepackage[
RegularFeatures={
	Letters     = Uppercase,
	Kerning     = Uppercase,
	Scale       = 0.85,
	LetterSpace = 1.26,
	WordSpace   = 1.21,
	Numbers     = Lining,
},
RegularSizeFeatures={
	{size=8.5 ,wght=560,wdth=115},
	{size=9.5 ,wght=542,wdth=112},
	{size=10.5,wght=524,wdth=116},
	{size=11.5,wght=506,wdth=106},
	{size=12.5,wght=488,wdth=103},
	{size=13.5,wght=470,wdth=100},
	{size=14.5,wght=460,wdth=99 },
	{size=16.5,wght=450,wdth=98 },
	{size=19.5,wght=440,wdth=97 },
	{size=22.5,wght=430,wdth=96 },
	{size=22.5,wght=420,wdth=95 },
},
]{junicodevf}

\ExplSyntaxOn
\NewDocumentCommand{\mytextsc}{sm}
{ \IfBooleanTF{#1}
	{ \text_map_function:nN { #2 } \__caps_to_sc:n }
	{ \text_map_function:nN { #2 } \__lower_to_sc:n }
}

\cs_new_protected:Nn \__lower_to_sc:n
{
	\str_if_eq:eeTF { #1 } { \text_uppercase:n { #1 } }
	{ {\jRegular#1} } { #1 }
}

\cs_new_protected:Nn \__caps_to_sc:n
{
	\str_if_eq:eeTF { #1 } { \text_lowercase:n { #1 } }
	{ {\jRegular#1} } { #1 }
}
\ExplSyntaxOff
```
![{54B03FB6-12E6-4F25-939D-45539D851B47}](https://github.com/user-attachments/assets/6dfebc65-3e3c-4bfb-9675-22454c12910b)
