### ISSUE TITLE
Italic shapes for ⟨ʕ⟩ and ⟨ʔ⟩

### ISSUE THREAD

**Issue by theblursed** [psb1558/Junicode-font#315]
Dear psb1558,

I’m writing you again, not for anything functional but for a small aesthetic detail.

it seems to me that Junicode's italic shapes for ⟨ʕ⟩ and ⟨ʔ⟩ are not very well integrated with the rest of italic letter-forms. The tilting looks a bit off, being different from both the capital and non-capital letters (I don't know if this was intended).
![Schermata 2024-12-21 alle 14 41 29](https://github.com/user-attachments/assets/f1686a6f-5b30-446e-8901-3f7fa59e7798)
(Coincidentally, I just noticed the non-italic pair ⟨ʕp⟩ could use a better kerning).

This was a big-size example for clarity, but in my eyes the difference in style is maybe more noticeable in small text.

The serif on the foot, also, make them look more "slanted" than "italic" and stand out as different among other letters. At the same time, serifs could help a bit to fill the blank space that "inevitably" will often exist around the foot, so it may be that they are actually a good choice... See a comparison with other fonts:
![Schermata 2024-12-21 alle 14 45 35](https://github.com/user-attachments/assets/3a879f1c-025f-4d4f-9891-69476d47636c)
It seems to me that Junicode's ⟨ʔ⟩ could benefit from a more uniform tilting, but for serifs or other foot-forms I have no advice and think the taste of the designer will be best.

Italic ⟨ʕ⟩ and ⟨ʔ⟩ occur in some romanizations of Arabic (for example, those of the [English Wiktionary](https://en.wiktionary.org/wiki/Wiktionary:About_Arabic), or [Canepari's ones](http://canipa.net/lib/exe/fetch.php?media=docs:apa2_200118.pdf)) where they are preferred to the easier-to-overlook ⟨ʿ⟩ and ⟨ʾ⟩ (...or ⟨ʻ⟩ and ⟨ʼ⟩).

Anyway this is in no way "urgent" or "needed" for me... I simply noticed and thought I should let you know. 

Thank you for your work and have a nice Christmas season 😊

**Comment by theblursed** [comment]
A "full italic" foot can be found in Bona Nova:
![Schermata 2024-12-21 alle 17 10 09](https://github.com/user-attachments/assets/a57b9b8f-670b-4a8c-8c31-fe6a51d3e045)
While good-looking for ⟨ʔ⟩, I'm not so sure about ⟨ʕ⟩...

**Comment by psb1558** [comment]
I'll look into it. I don't like the Bona Nova solution, but the others look good.

**Comment by psb1558** [comment]
This is done. Watch for the next release.
