### ISSUE TITLE
Kerning suggestions 

### ISSUE THREAD

**Issue by HM3p** [psb1558/Junicode-font#317]
Hello Mr. Baker, once again I'd like to bring to your attention some examples of problematic kerning I've encountered.
![Screenshot](https://github.com/user-attachments/assets/aebe2c94-6239-4cb5-a484-b0768c36448c)
As you can see above, the small capital s and small capital a are far too close together when italicized. This is especially apparent when it is made bold as well. 
Other characters that require tuning when italicized are ꜩ, ʒ, and the flat-top yogh, particularly when next to a long s or f.

**Comment by psb1558** [comment]
I have added or adjusted kerning for these pairs.
