### ISSUE TITLE
Name of font: Junicode New, JuniusX or Junius?

### ISSUE THREAD

**Issue by Linguistx** [psb1558/Junicode-font#66]
I'm very confused over the official name of the font. My best guess is that it's called "Junius" with JuniusVF being the variable version and all other versions collectively being referred to as JuniusX? And then "Junicode New" is some kind of unofficial name that acknowledges it being based on "Junicode", yet the repo uses this unofficial name?

**Comment by psb1558** [comment]
This situation comes from the plan not being fully formed in my head when I created the repo. (Either that or I wasn't completely sober when I named it.)

I see that it's possible to rename a GitHub repo. I should do that. Things are confusing enough without a confusing name.

**Comment by psb1558** [comment]
Done.

**Comment by Linguistx** [comment]
Seems like the repo should be named "Junius" though, right? Many font repos have VF version and any number of non-VF versions, but just have the common part of the name as the collective name for the repo: e.g. [Cabin](https://github.com/impallari/Cabin)

**Comment by psb1558** [comment]
Unfortunately, there is an unrelated font out there in the wild named "Junius," so I don't feel I can use that name unmodified though I've been using variants of it since the early nineties.

**Comment by Linguistx** [comment]
Then maybe it should be collectively called JuniusX, and the VF file should be named JuniusX-VF.ttf

**Comment by psb1558** [comment]
I was thinking of "X" as a modifier and "VF" as another modifier, but maybe it's all too confusing, and the "Junius" name is too compromised to keep. Fortunately there's plenty of time to think about this.

**Comment by psb1558** [comment]
I think this is done, more or less. The temporary name of the font is Junicode Two Beta: the name is an attempt to discourage the commercial free font sites. It will change to "Junicode" when the version reaches 2.0.
