### ISSUE TITLE
U+F0000 and U+F0001 no longer available with cv02

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#69]
Is this intentional? I can live with it, I'm just curious.

**Comment by psb1558** [comment]
There was a major rearrangement of the cvNN features, triggered by errors I made setting them up in the first place and the need to bring them into line with the OpenType spec: see #56. Now those characters are on cv53[1] and cv54[1].

**Comment by jsbien** [comment]
So there is a typo in "Feature Reference"...

**Comment by psb1558** [comment]
I just posted a corrected version of the Feature Reference.

**Comment by jsbien** [comment]
Thanks!
