### ISSUE TITLE
\={y} gives capital Y with macron in XeLaTex

### ISSUE THREAD

**Issue by prefectF** [psb1558/Junicode-font#70]
I'm using Junicode with XeLaTex (in Overleaf). For some reason \\={y} results in a capital Y with macron, rather than small y with macron. If I define and use a new command instead (e.g. \\newcommand{\\yy}{\\char"0233}), everything's as it should be. Any idea why this happens, and is there a simpler way to circumvent the issue than using a custom command for all those long ys in Old English?

**Comment by psb1558** [comment]
When I test with another font (GentiumPlus), I get exactly the same result, so I suspect it is a (Xe)LaTeX bug. But it seems to affect only the command `\={y}`, so I suggest any other input method for that one glyph. Since XeLaTex loves UTF-8 files, I'd suggest substituting the UTF-8 character (U+0233) for the command.

**Comment by prefectF** [comment]
Alright, thanks!

There's actually a somewhat similar issue with small and capital Tironian _et_, only in that case entering the code for the glyph doesn't help either: if I want a small Tironian _et_ (U+204A), I get what looks like capital Tironian _et_, and with the code for capital Tironian _et_ (U+2E52), I get a black rectangle with a white question mark inside.

**Comment by prefectF** [comment]
Thanks! I don't think there could be any conflict locally on my computer; just got a new one, and I have no TeX installation at all now. As Junicode is installed on Overleaf's servers, I just use the version they provide in their online editor.

**Comment by psb1558** [comment]
Oh, it's likely a very old version which doesn't have the cap Tironian sign. Can you dl the (legacy) version from here, put it in the directory (or an adjacent directory) with your *.tex files, and point the compiler to it?

I don't know what's going on with the lc Tironian sign looking uppercase. If you could post an image, that might get me started thinking about it.

**Comment by prefectF** [comment]
Tried it with the legacy font files from here - same result w.r.t. capital Tironian _et_.

(Forget that point about the small Tironian _et_ looking uppercase btw., that was just based on me stupidly looking at the unicode chart linked at https://junicode.sourceforge.io/ (General Punctuation) and seeing that what I got in my XeLaTeX file resembled the uppercase rather than the lower case version there.)

**Comment by psb1558** [comment]
Okay, sorry--I screwed up here. Junicode 1 doesn't have the cap Tironian sign. It is of course in Junicode 2, but I don't suggest switching entirely to an unstable development version for the sake of a single glyph. You could grab the regular face of Junicode 2 and use it just for that one thing, or you could just raise and enlarge the lc glyph slightly to fake a capital. You probably don't have a whole lot of cap Tironian signs in your text, so a bit of fakery for one or two instances wouldn't be so bad.

**Comment by prefectF** [comment]
Oh, understood; it's not that important and I can definitely manage without the real thing. Thanks a lot for the quick responses!
