### ISSUE TITLE
Capital A-ligatures - Serifs

### ISSUE THREAD

**Issue by elechner** [psb1558/Junicode-font#80]
![A-liga](https://user-images.githubusercontent.com/19876228/138742191-cb6cc8b4-eedd-4c60-815f-2c170a3ccb15.png)

1. Æ missing upper curve from the shared stroke serif. 
2. Ꜷ Missing upper curve from the diagonal A-stroke serif. 
3. Ꜷ having odd serif without(?) stoke sticking out.  Shouldn't the shared stroke goes on and forming U alternatively having a visible straight A-stroke:  
 
![AU](https://user-images.githubusercontent.com/19876228/138750088-be8cbf8b-7916-4c5c-8fac-2994c9dc9be5.png)

4. Not an issue but rather a design suggestion to add a tighter version of the AO ligature as main character variant for uniformity: 
![AO-ligature](https://user-images.githubusercontent.com/19876228/138744262-26e88df6-8114-430e-809e-966514dd0c5d.png)

**Comment by psb1558** [comment]
I think this is done. Thanks to @elechner for the suggestions.
