### ISSUE TITLE
v1.003 Bold italic: U+035F Combining Double Macron Below not rendering correctly

### ISSUE THREAD

**Issue by adamiturabi** [psb1558/Junicode-font#87]
I'm using Junicode v1.003. 

The character U+035F Combining Double Macron Below does not display correctly in the bold italic font:
![image](https://user-images.githubusercontent.com/61895563/143667372-1bde0e3b-4bc0-4094-ac4f-1100b6eb1f83.png)

It displays ok in the regular font:
![image](https://user-images.githubusercontent.com/61895563/143667377-8080a752-c12e-499d-99b7-47389aea2199.png)

Would it be possible to provide a fix for the legacy font and also check that it is suported in Junicode 2?

Thank you very much.

**Comment by psb1558** [comment]
U+035F is missing (like a lot of glyphs) from Bold Italic in v. 1.NNN. I'm sorry that I can't add any new glyphs to that version. But it is in all faces of Junicode 2.
