### ISSUE TITLE
04C BLACK LEFTWARDS BULLET? Was: Is this 'CAPITULUM' (U+2E3F)?

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#96]
Testing the option of creating an issue from a discussion :=)
Nevertheless I will appreciate providing a shape similar to those on the scan as (a variant of) 04C BLACK LEFTWARDS BULLET or in any other way.

### Discussed in https://github.com/psb1558/Junicode-font/discussions/93

<div type='discussions-op-text'>

<sup>Originally posted by **jsbien** December 13, 2021</sup>
![Zaborowski1535capitulum](https://user-images.githubusercontent.com/8024702/145757496-0f6152d7-3455-444d-a2c4-9a77bc689107.png)
It occurs quite often in a Latin text printed in Poland.</div>

**Comment by psb1558** [comment]
For a historical font like Junicode, I think this (or similar) is the best shape for both U+204C and U+204D.
<img width="158" alt="image" src="https://user-images.githubusercontent.com/16215767/148662903-eb224c66-48f3-414b-b366-fb39dba89a1a.png">
I'll work on making that substitution.

**Comment by jsbien** [comment]
Great!

**Comment by psb1558** [comment]
The new 204C and 204D.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/16215767/148829529-cb359c30-ecac-4953-a102-c26cc9405ee7.png">

**Comment by jsbien** [comment]
For me it's OK. Thanks!
